@startuml
'https://plantuml.com/class-diagram
!include AnaMon.puml
!include ../../_extensions/scaleSettingsDA/ScaleSettings.puml
!include ../../_extensions/unitDA/UnitSettings.puml

class AnaView{
    + readonly communication!: AnaViewRuntime
    - readonly scaleSettings: ScaleSettings
    - readonly unitSettings: UnitSettings
}
AnaView *- AnaViewSpec
AnaViewSpec ..> AnaViewMockup : <<use>>
AnaView *- AnaViewMockup

AnaView <|-- AnaMon
AnaView *-- "1" ScaleSettings
AnaView *-- "1" AnaViewRuntime
AnaView *-- "1" UnitSettings

@enduml
