@startuml
'https://plantuml.com/class-diagram

class StringView{
    + readonly communication!: StrRuntime
    + Text(): string | undefined
}
StringView *- StringViewSpec
StringViewSpec ..> StringViewMockup : <<use>>
StringView *- StringViewMockup

StringView *- "1" StrRuntime

@enduml
