@startuml
'https://plantuml.com/class-diagram
!include healthStateView/HealthStateView.puml
!include lockView/LockView4/Lockview4.puml

class DiagnosticElement{
    + readonly communication!: DiagnosticElementRuntime
    + readonly wqc: WQC
}


DiagnosticElement *- DiagnosticElementSpec
DiagnosticElementSpec ..> DiagnosticElementMockup : <<use>>
DiagnosticElement *- DiagnosticElementMockup
DiagnosticElement *- DiagnosticElementRuntime
DiagnosticElement *- WQC

DiagnosticElement <|-- LockView4
DiagnosticElement <|-- HealthStateView


@enduml
