@startuml
'https://plantuml.com/class-diagram

class BinProcessValueIn{
	+ readonly communication!: BinProcessValueInRuntime
}

BinProcessValueIn *- BinProcessValueInSpec
BinProcessValueInSpec ..> BinProcessValueInMockup : <<use>>
BinProcessValueIn *- BinProcessValueInMockup
BinProcessValueIn *- BinProcessValueInRuntime
@enduml
