@startuml
'https://plantuml.com/class-diagram
!include ServiceControl/ServiceControl.puml
!include ./activeElement/ActiveElement.puml
!include ./DiagnosticElement/diagnosticElement.puml

!include ./IndicatorElement/indicatorElement.puml
!include ./InputElement/inputElement.puml
!include ./OperationElement/operationElement.puml
!include ./DataAssemblyController.puml

abstract class DataAssemblyControllerFactory{
	+ {static} create(variableOptions: DataAssemblyOptions, connection: OpcUaConnection): DataAssemblyController {

}

DataAssemblyControllerFactory "<<create>>"..> DataAssemblyController


@enduml
