@startuml

skinparam monochrome false

participant POL
participant DataAssemblyController

rnote over DataAssemblyController
 State = false
endrnote


POL --> DataAssemblyController : Set := true
POL <-- DataAssemblyController : Set := false
rnote over DataAssemblyController
 State = true
endrnote
POL <-- DataAssemblyController : State == true
...
POL --> DataAssemblyController : Reset := true
POL <-- DataAssemblyController : Reset := false
rnote over DataAssemblyController
 State = false
endrnote
POL <-- DataAssemblyController : State == false

@enduml
