---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:

- name: build
  image: node:8-jessie
  commands:
  - npm install
  - npm run-script apidoc build

- name: test
  image: node:8-jessie
  commands:
  - export LOGLEVEL=warn
  - npm test

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-backend
    autotag: true

- name: docker-arm
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-backend-arm
    autotag: true

- name: notify
  image: drillster/drone-email
  settings:
    from: "plt@mailbox.tu-dresden.de"
    host: mail.zih.tu-dresden.de
    password:
      from_secret: email_password
    username: plt
  when:
    status:
    - changed
    - failure

---
kind: signature
hmac: fc96b73254e150474c3268effa3e68211f1b7582b346cb3b55d5688b803d4a02

...
