clone:
  git:
    image: plugins/git
    skip_verify: true


pipeline:

  build:
    image: node:8-jessie
    commands:
      - npm install
      - npm run-script apidoc build

  test:
    image: node:8-jessie
    commands:
      - export LOGLEVEL=warn
      - npm test

  docker:
    image: plugins/docker
    settings:
        username: kevinbacon
        password: pa55word
        repo: p2olab/polaris-backend
        auto_tag: true
        purge: true

  notify:
    image: drillster/drone-email
    host: mail.zih.tu-dresden.de
    username: plt
    password: $EMAIL_PASSWORD
    secrets: [ email_password ]
    from: plt@mailbox.tu-dresden.de
    recipients: [ markus.graube@tu-dresden.de ]
    when:
      status: [ changed, failure ]
