---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:

- name: notify
  image: drillster/drone-email
  settings:
    from: "plt@mailbox.tu-dresden.de"
    host: mail.zih.tu-dresden.de
    password:
      from_secret: email_password
    username: plt
  when:
    status:
    - changed
    - failure

- name: build
  image: node:8-jessie
  commands:
  - npm install
  - npm run-script apidoc build

- name: test
  image: node:8-jessie
  commands:
  - export LOGLEVEL=warn
  - npm test

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: p2olab/polaris-backend

- name: notify
  image: drillster/drone-email
  settings:
    from: "plt@mailbox.tu-dresden.de"
    host: mail.zih.tu-dresden.de
    password:
      from_secret: email_password
    username: plt
  when:
    status:
    - changed
    - failure

---
kind: signature
hmac: 582d3919f15944c041224ffbd5429212f12514fbdce8aa06c5245cca928eba70

...
