@startuml



package "module (PEA)" {
    [Services] -- [OPC UA Server]
}

node "Process Orchestation Layer (POL)" {
    package "pfe-ree-node" {
        [Express] -- [Manager/Module/Service]
        [Manager/Module/Service] -- [OPC UA Client]
    }

    package "pfe-ree-viz" {
        [Angular] -right- [Express] : HTTP, Websocket
    }

    package "pfe-ree-interface" {
        () interface as if
    }
}

if .down. [Express] : import
if .down. [Angular] : import

[OPC UA Server] <-left-> [OPC UA Client] : OPC UA

(MTP) <.down. [Services]
(MTP) .down.> [Manager/Module/Service]

@enduml