# Docker Parent Image with Node and Typescript
FROM node:8-jessie as base
WORKDIR /app

# image for runtime dependencies
FROM base as dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install --prod

## Image for building
FROM dependencies as build
COPY src src
COPY tsconfig.json .
RUN npm install
RUN npm run build

# production image
FROM node:21.2-alpine3.18
LABEL org.label-schema.name "test-pea"
LABEL org.label-schema.docker.cmd "docker run -d -p 4334:4334 p2olab/test-pea"

COPY --from=dependencies /app/node_modules node_modules
COPY --from=build /app/build build
EXPOSE 4334
ENTRYPOINT ["node", "build/src/testServer.js"]
