/*
 * MIT License
 *
 * Copyright (c) 2021 P2O-Lab <p2o-lab@mailbox.tu-dresden.de>,
 * Chair for Process Control Systems, Technische Universität Dresden
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
 
@startuml

skinparam monochrome false

participant POL
participant ProcedureParam
participant Service

rnote over ProcedureParam
 VMin = 0.0
 VMax = 20.0
 VOut = 0.0
 VReq = 0.0
 ParamOpMode: Automatic
endrnote
rnote over Service
  State: Idle
endrnote

POL -> ProcedureParam : VExt:=10.0

rnote over ProcedureParam
 VOut = 0.0
 VReq = 10.0
endrnote

POL <- ProcedureParam : VReq:=10.0

hnote over POL #00FF00: VReq==VExt?

activate Service

POL -> Service : Service.Start
rnote over Service
  StateCur: Starting
endrnote
ProcedureParam <- Service

rnote over ProcedureParam
 VOut = 10.0 (Frozen)
 VReq = 10.0
endrnote
rnote over Service
  StateCur: Execute
endrnote

POL -> ProcedureParam : VExt:=15.0

rnote over ProcedureParam
 VOut = 10.0 (Frozen)
 VReq = 15.0
endrnote

POL <- ProcedureParam : VReq:=15.0

hnote over POL #00FF00: VReq==VExt?

POL -> Service : Service.Restart
rnote over Service
  StateCur: Starting
endrnote
ProcedureParam <- Service

rnote over ProcedureParam
 VOut = 15.0 (Frozen)
 VReq = 15.0
endrnote
rnote over Service
  StateCur: Execute
endrnote
...
POL -> ProcedureParam : VExt:=25.0

rnote over ProcedureParam
 VOut = 15.0 (Frozen)
 VReq = 20.0
endrnote

POL <- ProcedureParam : VReq:=20.0

hnote over POL #FF0000: VReq==VExt?
rnote over POL
Choice:
Execute Anyway?
endrnote
POL -> Service : Service.Restart
rnote over Service
  StateCur: Starting
endrnote

ProcedureParam <- Service

rnote over ProcedureParam
 VOut = 20.0 (Frozen)
 VReq = 20.0;
endrnote
rnote over Service
  StateCur:Execute
endrnote
@enduml
