@startuml
'https://plantuml.com/class-diagram
!include InformationFlowConnector.puml
!include MassFlowConnector.puml

interface ConnectorInterface

ConnectorInterface <|-- InformationFlowConnector
ConnectorInterface <|-- MassFlowConnector

@enduml
