@startuml
'https://plantuml.com/class-diagram
!include ../Lockview8/LockView8.puml

class LockView4{
	+ readonly communication!: LockView4Runtime;
}
LockView4 *- LockView4Runtime

LockView4 *- LockView4Spec
LockView4Spec ..> LockView4Mockup : <<use>>
LockView4 *- LockView4Mockup

LockView4 <|-- LockView8
@enduml
