/*
 * MIT License
 *
 * Copyright (c) 2018 Markus Graube <markus.graube@tu.dresden.de>,
 * Chair for Process Control Systems, Technische Universität Dresden
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * physical unit as they are used in MTP
 * @type {{value: number; unit: string; name: string; name_english: string}[]}
 */
export const Unit = [
    {value: 1000, unit: 'K', name: 'Kelvin', name_english: 'Kelvin'},
    {value: 1001, unit: '°C', name: 'Grad Celsius', name_english: 'Degrees Celsius'},
    {value: 1002, unit: '°F', name: 'Grad Fahrenheit', name_english: 'Degrees Fahrenheit'},
    {value: 1003, unit: '°R', name: 'Grad Rankine', name_english: 'Degree Rankine'},
    {value: 1004, unit: 'rad', name: 'Radiant', name_english: 'Radian'},
    {value: 1005, unit: '°', name: 'Grad', name_english: 'Degree'},
    {value: 1006, unit: '\'', name: 'Minute', name_english: 'Minute'},
    {value: 1007, unit: '\'\'', name: 'Sekunde', name_english: 'Second'},
    {value: 1008, unit: 'gon', name: 'Gon', name_english: 'Gon'},
    {value: 1009, unit: 'r', name: 'Umdrehung', name_english: 'Revolution'},
    {value: 1010, unit: 'm', name: 'Meter', name_english: 'Meter'},
    {value: 1011, unit: 'km', name: 'Kilometer', name_english: 'Kilometer'},
    {value: 1012, unit: 'cm', name: 'Zentimeter', name_english: 'Centimeter'},
    {value: 1013, unit: 'mm', name: 'Millimeter', name_english: 'Millimeter'},
    {value: 1014, unit: 'μm', name: 'Mikrometer', name_english: 'Micrometer'},
    {value: 1015, unit: 'nm', name: 'Nanometer', name_english: 'Nanometer'},
    {value: 1016, unit: 'pm', name: 'Picometer', name_english: 'Picometer'},
    {value: 1017, unit: 'Å', name: 'Angstrom', name_english: 'Angstrom'},
    {value: 1018, unit: 'ft', name: 'Fuß', name_english: 'Foot'},
    {value: 1019, unit: 'in', name: 'Zoll', name_english: 'Inch'},
    {value: 1020, unit: 'yd', name: 'Yard', name_english: 'Yard'},
    {value: 1021, unit: 'mile', name: 'Meile', name_english: 'Mile'},
    {value: 1022, unit: 'nautical mile', name: 'Nautische Meile', name_english: 'Nautical mile'},
    {value: 1023, unit: 'm2', name: 'Quadratmeter', name_english: 'Square meter'},
    {value: 1024, unit: 'km2', name: 'Quadratkilometer', name_english: 'Square kilometer'},
    {value: 1025, unit: 'cm2', name: 'Quadratzentimeter', name_english: 'Square centimeter'},
    {value: 1026, unit: 'dm2', name: 'Quadratdezimeter', name_english: 'Square decimeter'},
    {value: 1027, unit: 'mm2', name: 'Quadratmillimeter', name_english: 'Square millimeter'},
    {value: 1028, unit: 'a', name: 'Ar', name_english: 'Are'},
    {value: 1029, unit: 'ha', name: 'Hektar', name_english: 'Hectare'},
    {value: 1030, unit: 'in2', name: 'Quadratzoll', name_english: 'Square inch'},
    {value: 1031, unit: 'ft2', name: 'Quadratfuß', name_english: 'Square foot'},
    {value: 1032, unit: 'yd2', name: 'Quadratyard', name_english: 'Square yard'},
    {value: 1033, unit: 'mile2', name: 'Quadratmeile', name_english: 'Square mile'},
    {value: 1034, unit: 'm3', name: 'Kubikmeter', name_english: 'Cubic meter'},
    {value: 1035, unit: 'dm3', name: 'Kubikdezimeter', name_english: 'Cubic decimeter'},
    {value: 1036, unit: 'cm3', name: 'Kubikzentimeter', name_english: 'Cubic centimeter'},
    {value: 1037, unit: 'mm3', name: 'Kubikmillimeter', name_english: 'Cubic millimeter'},
    {value: 1038, unit: 'L', name: 'Liter', name_english: 'Liter'},
    {value: 1039, unit: 'cl', name: 'Zentiliter', name_english: 'Centiliter'},
    {value: 1040, unit: 'ml', name: 'Milliliter', name_english: 'Milliliter'},
    {value: 1041, unit: 'hl', name: 'Hektoliter', name_english: 'Hectoliter'},
    {value: 1042, unit: 'in3', name: 'Kubikzoll', name_english: 'Cubic inch'},
    {value: 1043, unit: 'ft3', name: 'Kubikfuß', name_english: 'Cubic foot'},
    {value: 1044, unit: 'yd3', name: 'Kubikyard', name_english: 'Cubic yard'},
    {value: 1045, unit: 'mile3', name: 'Kubikmeile', name_english: 'Cubic mile'},
    {value: 1046, unit: 'pint', name: 'Pint', name_english: 'Pint'},
    {value: 1047, unit: 'quart', name: 'Quart', name_english: 'Quart'},
    {value: 1048, unit: 'gal', name: 'US-Gallonen', name_english: 'US gallon'},
    {value: 1049, unit: 'ImpGal', name: 'Imperial Gallonen', name_english: 'Imperial gallon'},
    {value: 1050, unit: 'bushel', name: 'Bushel', name_english: 'Bushel'},
    {value: 1051, unit: 'bbl', name: 'Barrel = 42 Gallonen', name_english: 'Barrel = 42 gallons'},
    {
        value: 1052,
        unit: 'bbl(liq)',
        name: 'Barrel flüssig = 31,5 Gallonen',
        name_english: 'Liquid barrel = 31.5 gallons'
    },
    {value: 1053, unit: 'ft3 std.', name: 'Normkubikfuß', name_english: 'Standard cubic foot'},
    {value: 1054, unit: 's', name: 'Sekunde', name_english: 'Second'},
    {value: 1055, unit: 'ks', name: 'Kilosekunde', name_english: 'Kilosecond'},
    {value: 1056, unit: 'ms', name: 'Millisekunde', name_english: 'Millisecond'},
    {value: 1057, unit: 'μs', name: 'Mikrosekunde', name_english: 'Microsecond'},
    {value: 1058, unit: 'min', name: 'Minute', name_english: 'Minute'},
    {value: 1059, unit: 'h', name: 'Stunde', name_english: 'Hour'},
    {value: 1060, unit: 'd', name: 'Tag', name_english: 'Day'},
    {value: 1061, unit: 'm/s', name: 'Meter pro Sekunde', name_english: 'Meters per second'},
    {value: 1062, unit: 'mm/s', name: 'Millimeter pro Sekunde', name_english: 'Millimeters per second'},
    {value: 1063, unit: 'm/h', name: 'Meter pro Stunde', name_english: 'Meters per hour'},
    {value: 1064, unit: 'km/h', name: 'Kilometer pro Stunde', name_english: 'Kilometers per hour'},
    {value: 1065, unit: 'knot', name: 'Knoten', name_english: 'Knot'},
    {value: 1066, unit: 'in/s', name: 'Zoll pro Sekunde', name_english: 'Inches per second'},
    {value: 1067, unit: 'ft/s', name: 'Fuß pro Sekunde', name_english: 'Feet per second'},
    {value: 1068, unit: 'yd/s', name: 'Yard pro Sekunde', name_english: 'Yards per second'},
    {value: 1069, unit: 'in/min', name: 'Zoll pro Minute', name_english: 'Inches per minute'},
    {value: 1070, unit: 'ft/min', name: 'Fuß pro Minute', name_english: 'Feet per minute'},
    {value: 1071, unit: 'yd/min', name: 'Yard pro Minute', name_english: 'Yards per minute'},
    {value: 1072, unit: 'in/h', name: 'Zoll pro Stunde', name_english: 'Inches per hour'},
    {value: 1073, unit: 'ft/h', name: 'Fuß pro Stunde', name_english: 'Feet per hour'},
    {value: 1074, unit: 'yd/h', name: 'Yard pro Stunde', name_english: 'Yards per hour'},
    {value: 1075, unit: 'mi/h', name: 'Meilen pro Stunden', name_english: 'Miles per hour'},
    {value: 1076, unit: 'm/s2', name: 'Meter pro Quadratsekunde', name_english: 'Meter/second squared'},
    {value: 1077, unit: 'Hz', name: 'Hertz', name_english: 'Hertz'},
    {value: 1078, unit: 'THz', name: 'Terahertz', name_english: 'Terahertz'},
    {value: 1079, unit: 'GHz', name: 'Gigahertz', name_english: 'Gigahertz'},
    {value: 1080, unit: 'MHz', name: 'Megahertz', name_english: 'Megahertz'},
    {value: 1081, unit: 'kHz', name: 'Kilohertz', name_english: 'Kilohertz'},
    {value: 1082, unit: '1/s', name: 'Pro Sekunde', name_english: 'Per second'},
    {value: 1083, unit: '1/min', name: 'Pro Minute', name_english: 'Per minute'},
    {value: 1084, unit: 'r/s', name: 'Umdrehungen pro Sekunde', name_english: 'Revolutions per second'},
    {value: 1085, unit: 'rpm', name: 'Umdrehungen pro Minute', name_english: 'Revolutions per minute'},
    {value: 1086, unit: 'rad/s', name: 'Radiant pro Sekunde', name_english: 'Radians per second'},
    {value: 1087, unit: '1/s2', name: 'Pro Quadratsekunden', name_english: 'Per second squared'},
    {value: 1088, unit: 'kg', name: 'Kilogramm', name_english: 'Kilogram'},
    {value: 1089, unit: 'g', name: 'Gramm', name_english: 'Gram'},
    {value: 1090, unit: 'mg', name: 'Milligramm', name_english: 'Milligram'},
    {value: 1091, unit: 'Mg', name: 'Megagramm', name_english: 'Megagram'},
    {value: 1092, unit: 't', name: 'Metrische Tonne', name_english: 'Metric ton'},
    {value: 1093, unit: 'oz', name: 'Unze', name_english: 'Ounce'},
    {value: 1094, unit: 'lb', name: 'Pfund', name_english: 'Pound'},
    {value: 1095, unit: 'STon', name: 'US-Tonne', name_english: 'US ton (short ton)'},
    {value: 1096, unit: 'LTon', name: 'Britische Tonne', name_english: 'British ton (long ton)'},
    {value: 1097, unit: 'kg/m3', name: 'Kilogramm pro Kubikmeter', name_english: 'Kilograms per cubic meter'},
    {value: 1098, unit: 'Mg/dm3', name: 'Megagramm pro Kubikmeter', name_english: 'Megagrams per cubic meter'},
    {value: 1099, unit: 'kg/dm3', name: 'Kilogramm pro Kubikdezimeter', name_english: 'Kilograms per cubic decimeter'},
    {value: 1100, unit: 'g/cm3', name: 'Gramm pro Kubikzentimeter', name_english: 'Grams per cubic centimeter'},
    {value: 1101, unit: 'g/m3', name: 'Gramm pro Kubikmeter', name_english: 'Grams per cubic meter'},
    {value: 1102, unit: 't/m3', name: 'Metrische Tonne pro Kubikmeter', name_english: 'Metric tons per cubic meter'},
    {value: 1103, unit: 'kg/L', name: 'Kilogramm pro Liter', name_english: 'Kilogram per liter'},
    {value: 1104, unit: 'g/ml', name: 'Gramm pro Milliliter', name_english: 'Grams per milliliter'},
    {value: 1105, unit: 'g/L', name: 'Gramm pro Liter', name_english: 'Grams per liter'},
    {value: 1106, unit: 'lb/in3', name: 'Pfund pro Kubikzoll', name_english: 'Pounds per cubic inch'},
    {value: 1107, unit: 'lb/ft3', name: 'Pfund pro Kubikfuß', name_english: 'Pounds per cubic foot'},
    {value: 1108, unit: 'lb/gal', name: 'Pfund pro US-Gallonen', name_english: 'Pounds per US gallon'},
    {value: 1109, unit: 'STon/yd3', name: 'US-Tonnen pro Kubikyard', name_english: 'US tons per cubic yard'},
    {value: 1110, unit: '°Twad', name: 'Grad Twaddell', name_english: 'Degree Twaddell'},
    {value: 1111, unit: '°Baum (hv)', name: 'Grad Baumé (schwer)', name_english: 'Degree Baumé (heavy)'},
    {value: 1112, unit: '°Baum (lt)', name: 'Grad Baumé (leicht)', name_english: 'Degree Baumé (light)'},
    {value: 1113, unit: '°API', name: 'Grad API', name_english: 'Degrees API'},
    {value: 1114, unit: 'SGU', name: 'Specific gravity units', name_english: 'Specific gravity units'},
    {value: 1115, unit: 'kg/m', name: 'Kilogramm pro Meter', name_english: 'Kilograms per meter'},
    {value: 1116, unit: 'mg/m', name: 'Milligramm pro Meter', name_english: 'Milligrams per meter'},
    {value: 1117, unit: 'tex', name: 'Tex', name_english: 'Tex'},
    {value: 1118, unit: 'kg·m2', name: 'Kilogramm mal Quadratmeter', name_english: 'Kilograms per square meter'},
    {
        value: 1119,
        unit: 'kg·m/s',
        name: 'Kilogramm mal Meter pro Sekunde',
        name_english: 'Kilograms per meter per second'
    },
    {value: 1120, unit: 'N', name: 'Newton', name_english: 'Newton'},
    {value: 1121, unit: 'MN', name: 'Meganewton', name_english: 'Meganewton'},
    {value: 1122, unit: 'kN', name: 'Kilonewton', name_english: 'Kilonewton'},
    {value: 1123, unit: 'mN', name: 'Millinewton', name_english: 'Millinewton'},
    {value: 1124, unit: 'μN', name: 'Mikronewton', name_english: 'Micronewton'},
    {
        value: 1125,
        unit: 'kg·m2/s',
        name: 'Kilogramm mal Quadratmeter pro Sekunde',
        name_english: 'Kilograms per square meter per second'
    },
    {value: 1126, unit: 'N·m', name: 'Newton mal Meter', name_english: 'Newton meter'},
    {value: 1127, unit: 'MN·m', name: 'Meganewton mal Meter', name_english: 'Meganewton meter'},
    {value: 1128, unit: 'kN·m', name: 'Kilonewton mal Meter', name_english: 'Kilonewton meter'},
    {value: 1129, unit: 'mN·m', name: 'Millinewton mal Meter', name_english: 'Millinewton meter'},
    {value: 1130, unit: 'Pa', name: 'Pascal', name_english: 'Pascal'},
    {value: 1131, unit: 'GPa', name: 'Gigapascal', name_english: 'Gigapascal'},
    {value: 1132, unit: 'MPa', name: 'Megapascal', name_english: 'Megapascal'},
    {value: 1133, unit: 'kPa', name: 'Kilopascal', name_english: 'Kilopascal'},
    {value: 1134, unit: 'mPa', name: 'Millipascal', name_english: 'Millipascal'},
    {value: 1135, unit: 'μPa', name: 'Mikropascal', name_english: 'Micropascal'},
    {value: 1136, unit: 'hPa', name: 'Hektopascal', name_english: 'Hectopascal'},
    {value: 1137, unit: 'bar', name: 'Bar', name_english: 'Bar'},
    {value: 1138, unit: 'mbar', name: 'Millibar', name_english: 'Millibar'},
    {value: 1139, unit: 'torr', name: 'Torr', name_english: 'Torr'},
    {value: 1140, unit: 'atm', name: 'Atmosphären', name_english: 'Atmosphere'},
    {value: 1141, unit: 'psi', name: 'Pfund pro Quadratzoll', name_english: 'Pounds per square inch'},
    {
        value: 1142,
        unit: 'psia',
        name: 'Pfund pro quadratinch (absolut)',
        name_english: 'Pounds per square inch (absolute)'
    },
    {value: 1143, unit: 'psig', name: 'Pfund pro quadratinch (gauge)', name_english: 'Pounds per square inch (gauge)'},
    {value: 1144, unit: 'g/cm2', name: 'Gramm pro Quadratzentimeter', name_english: 'Grams per square centimeter'},
    {
        value: 1145,
        unit: 'kg/cm2',
        name: 'Kilogramm pro Quadratzentimeter',
        name_english: 'Kilograms per square centimeter'
    },
    {value: 1146, unit: 'inH2O', name: 'Zoll Wassersäule', name_english: 'Inches of water'},
    {
        value: 1147,
        unit: 'inH2O (4°C)',
        name: 'Zoll Wassersäule bei 4 Grad Celsius',
        name_english: 'Inches of water at 4 degrees Celsius'
    },
    {
        value: 1148,
        unit: 'inH2O (68°F)',
        name: 'Zoll Wassersäule bei 68 Grad Fahrenheit',
        name_english: 'Inches of water at 68 degrees Fahrenheit'
    },
    {value: 1149, unit: 'mmH2O', name: 'Millimeter Wassersäule', name_english: 'Millimeters of water'},
    {
        value: 1150,
        unit: 'mmH2O (4°C)',
        name: 'Millimeter Wassersäule bei 4 Grad Celsius',
        name_english: 'Millimeters of water at 4 degrees Celsius'
    },
    {
        value: 1151,
        unit: 'mmH2O (68°F)',
        name: 'Millimeter Wassersäule bei 68 Grad Fahrenheit',
        name_english: 'Millimeters of water at 68 degrees Fahrenheit'
    },
    {value: 1152, unit: 'ftH2O', name: 'Fuß Wassersäule', name_english: 'Feet of water'},
    {
        value: 1153,
        unit: 'ftH2O (4°C)',
        name: 'Fuß Wassersäule bei 4 Grad Celsius',
        name_english: 'Feet of water at 4 degrees Celsius'
    },
    {
        value: 1154,
        unit: 'ftH2O (68°F)',
        name: 'Fuß Wassersäule bei 68 Grad Fahrenheit',
        name_english: 'Feet of water at 68 degrees Fahrenheit'
    },
    {value: 1155, unit: 'inHg', name: 'Zoll Quecksilbersäule', name_english: 'Inches of mercury'},
    {
        value: 1156,
        unit: 'inHg (0°C)',
        name: 'Zoll Quecksilbersäule bei 0 Grad Celsius',
        name_english: 'Inches of mercury at 0 degrees Celsius'
    },
    {value: 1157, unit: 'mmHg', name: 'Millimeter Quecksilbersäule', name_english: 'Millimeters of mercury'},
    {
        value: 1158,
        unit: 'mmHg (0°C)',
        name: 'Millimeter Quecksilbersäule bei 0 Grad Celsius',
        name_english: 'Millimeters of mercury at 0 degrees Celsius'
    },
    {value: 1159, unit: 'Pa·s', name: 'Pascalsekunde', name_english: 'Pascal second'},
    {value: 1160, unit: 'm2/s', name: 'Quadratmeter pro Sekunde', name_english: 'Square meters per second'},
    {value: 1161, unit: 'P', name: 'Poise', name_english: 'Poise'},
    {value: 1162, unit: 'cP', name: 'Zentipoise', name_english: 'Centipoise'},
    {value: 1163, unit: 'St', name: 'Stokes', name_english: 'Stokes'},
    {value: 1164, unit: 'cSt', name: 'Zentistokes', name_english: 'Centistokes'},
    {value: 1165, unit: 'N/m', name: 'Newton pro Meter', name_english: 'Newtons per meter'},
    {value: 1166, unit: 'mN/m', name: 'Millinewton pro Meter', name_english: 'Millinewtons per meter'},
    {value: 1167, unit: 'J', name: 'Joule', name_english: 'Joule'},
    {value: 1168, unit: 'EJ', name: 'Exajoule', name_english: 'Exajoule'},
    {value: 1169, unit: 'PJ', name: 'Petajoule', name_english: 'Petajoule'},
    {value: 1170, unit: 'TJ', name: 'Terajoule', name_english: 'Terajoule'},
    {value: 1171, unit: 'GJ', name: 'Gigajoule', name_english: 'Gigajoule'},
    {value: 1172, unit: 'MJ', name: 'Megajoule', name_english: 'Megajoule'},
    {value: 1173, unit: 'kJ', name: 'Kilojoule', name_english: 'Kilojoule'},
    {value: 1174, unit: 'mJ', name: 'Millijoule', name_english: 'Millijoule'},
    {value: 1175, unit: 'W·h', name: 'Wattstunde', name_english: 'Watt hour'},
    {value: 1176, unit: 'TW·h', name: 'Terawattstunde', name_english: 'Terawatt hour'},
    {value: 1177, unit: 'GW·h', name: 'Gigawattstunde', name_english: 'Gigawatt hour'},
    {value: 1178, unit: 'MW·h', name: 'Megawattstunde', name_english: 'Megawatt hour'},
    {value: 1179, unit: 'kW·h', name: 'Kilowattstunde', name_english: 'Kilowatt hour'},
    {value: 1180, unit: 'calth', name: 'Kalorie (thermochemisch)', name_english: 'Calorie (thermo chemical)'},
    {value: 1181, unit: 'kcalth', name: 'Kilokalorie (thermochemisch)', name_english: 'Kilocalorie (thermo chemical)'},
    {value: 1182, unit: 'Mcalth', name: 'Megakalorie (thermochemisch)', name_english: 'Megacalorie (thermo chemical)'},
    {value: 1183, unit: 'Btuth', name: 'British thermal unit', name_english: 'British thermal unit'},
    {value: 1184, unit: 'datherm', name: 'Decatherm', name_english: 'Decatherm'},
    {value: 1185, unit: 'ft·lbf', name: 'Fuß mal Pfund', name_english: 'Foot pound'},
    {value: 1186, unit: 'W', name: 'Watt', name_english: 'Watt'},
    {value: 1187, unit: 'TW', name: 'Terawatt', name_english: 'Terawatt'},
    {value: 1188, unit: 'GW', name: 'Gigawatt', name_english: 'Gigawatt'},
    {value: 1189, unit: 'MW', name: 'Megawatt', name_english: 'Megawatt'},
    {value: 1190, unit: 'kW', name: 'Kilowatt', name_english: 'Kilowatt'},
    {value: 1191, unit: 'mW', name: 'Milliwatt', name_english: 'Milliwatt'},
    {value: 1192, unit: 'μW', name: 'Mikrowatt', name_english: 'Microwatt'},
    {value: 1193, unit: 'nW', name: 'Nanowatt', name_english: 'Nanowatt'},
    {value: 1194, unit: 'pW', name: 'Picowatt', name_english: 'Picowatt'},
    {value: 1195, unit: 'Mcalth/h', name: 'Megakalorie pro Stunde', name_english: 'Megacalorie per hour'},
    {value: 1196, unit: 'MJ/h', name: 'Megajoule pro Stunde', name_english: 'Megajoule per hour'},
    {
        value: 1197,
        unit: 'Btuth/h',
        name: 'Britische thermische Einheit pro Stunde1',
        name_english: 'British thermal units per hour'
    },
    {value: 1198, unit: 'hp', name: 'Pferdestärke', name_english: 'Horsepower'},
    {value: 1199, unit: 'W/(m·K)', name: 'Watt pro Meter mal Kelvin', name_english: 'Watts per meter kelvin'},
    {
        value: 1200,
        unit: 'W/(m2·K)',
        name: 'Watt pro (Quadrateter mal Kelvin)',
        name_english: 'Watts per (square meter kelvin)'
    },
    {
        value: 1201,
        unit: 'm2·K/W',
        name: 'Quadratmeter mal Kelvin pro Watt',
        name_english: 'Square meters kelvin per Watt'
    },
    {value: 1202, unit: 'J/K', name: 'Joule pro Kelvin', name_english: 'Joules per kelvin'},
    {value: 1203, unit: 'kJ/K', name: 'Kilojoule pro Kelvin', name_english: 'Kilojoules per kelvin'},
    {
        value: 1204,
        unit: 'J/(kg·K)',
        name: 'Joule pro (Kilogramm mal Kelvin)',
        name_english: 'Joules per (kilogram kelvin)'
    },
    {
        value: 1205,
        unit: 'kJ/(kg·K)',
        name: 'Kilojoule pro (Kilogramm mal Kelvin)',
        name_english: 'Kilojoules per (kilogram kelvin)'
    },
    {value: 1206, unit: 'J/kg', name: 'Joule pro Kilogramm', name_english: 'Joules per kilogram'},
    {value: 1207, unit: 'MJ/kg', name: 'Megajoule pro Kilogram', name_english: 'Megajoules per kilogram'},
    {value: 1208, unit: 'kJ/kg', name: 'Kilojoule pro Kilogramm', name_english: 'Kilojoules per kilogramm'},
    {value: 1209, unit: 'A', name: 'Ampere', name_english: 'Ampere'},
    {value: 1210, unit: 'kA', name: 'Kiloampere', name_english: 'Kiloampere'},
    {value: 1211, unit: 'mA', name: 'Milliampere', name_english: 'Milliampere'},
    {value: 1212, unit: 'μA', name: 'Mikroampere', name_english: 'Microampere'},
    {value: 1213, unit: 'nA', name: 'Nanoampere', name_english: 'Nanoampere'},
    {value: 1214, unit: 'pA', name: 'Picoampere', name_english: 'Picoampere'},
    {value: 1215, unit: 'C', name: 'Coulomb', name_english: 'Coulomb'},
    {value: 1216, unit: 'MC', name: 'Megacoulomb', name_english: 'Megacoulomb'},
    {value: 1217, unit: 'kC', name: 'Kilocoulomb', name_english: 'Kilocoulomb'},
    {value: 1218, unit: 'μC', name: 'Mikrocoulomb', name_english: 'Microcoulomb'},
    {value: 1219, unit: 'nC', name: 'Nanocoulomb', name_english: 'Nanocoulomb'},
    {value: 1220, unit: 'pC', name: 'Picocoulomb', name_english: 'Picocoulomb'},
    {value: 1221, unit: 'A·h', name: 'Amperestunde', name_english: 'Ampere hour'},
    {value: 1222, unit: 'C/m3', name: 'Coulomb pro Kubikmeter', name_english: 'Coulombs per cubic meter'},
    {value: 1223, unit: 'C/mm3', name: 'Coulomb pro Kubikmillimeter', name_english: 'Coulombs per cubic millimeter'},
    {value: 1224, unit: 'C/cm3', name: 'Coulomb pro Kubikzentimeter', name_english: 'Coulombs per cubic centimeter'},
    {value: 1225, unit: 'kC/m3', name: 'Kilocoulomb pro Kubikmeter', name_english: 'Kilocoulombs per cubic meter'},
    {value: 1226, unit: 'mC/m3', name: 'Millicoulomb pro Kubikmeter', name_english: 'Millicoulombs per cubic meter'},
    {value: 1227, unit: 'μC/m3', name: 'Mikrocoulomb pro Kubikmeter', name_english: 'Microcoulombs per cubic meter'},
    {value: 1228, unit: 'C/m2', name: 'Coulomb pro Quadratmeter', name_english: 'Coulombs per square meter'},
    {value: 1229, unit: 'C/mm2', name: 'Coulomb pro Quadratmillimeter', name_english: 'Coulombs per square millimeter'},
    {value: 1230, unit: 'C/cm2', name: 'Coulomb pro Quadratzentimeter', name_english: 'Coulombs per square centimeter'},
    {value: 1231, unit: 'kC/m2', name: 'Kilocoulomb pro Quadratmeter', name_english: 'Kilocoulombs per square meter'},
    {value: 1232, unit: 'mC/m2', name: 'Millicoulomb pro Quadratmeter', name_english: 'Millicoulombs per square meter'},
    {value: 1233, unit: 'μC/m2', name: 'Mikrocoulomb pro Quadratmeter', name_english: 'Microcoulombs per square meter'},
    {value: 1234, unit: 'V/m', name: 'Volt pro Meter', name_english: 'Volts per meter'},
    {value: 1235, unit: 'MV/m', name: 'Megavolt pro Meter', name_english: 'Megavolts per meter'},
    {value: 1236, unit: 'kV/m', name: 'Kilovolt pro Meter', name_english: 'Kilovolts per meter'},
    {value: 1237, unit: 'V/cm', name: 'Volt pro Zentimeter', name_english: 'Volts per centimeter'},
    {value: 1238, unit: 'mV/m', name: 'Millivolt pro Meter', name_english: 'Millivolts per meter'},
    {value: 1239, unit: 'μV/m', name: 'Mikrovolt pro Meter', name_english: 'Microvolts per meter'},
    {value: 1240, unit: 'V', name: 'Volt', name_english: 'Volt'},
    {value: 1241, unit: 'MV', name: 'Megavolt', name_english: 'Megavolt'},
    {value: 1242, unit: 'kV', name: 'Kilovolt', name_english: 'Kilovolt'},
    {value: 1243, unit: 'mV', name: 'Millivolt', name_english: 'Millivolt'},
    {value: 1244, unit: 'μV', name: 'Mikrovolt', name_english: 'Microvolt'},
    {value: 1245, unit: 'F', name: 'Farad', name_english: 'Farad'},
    {value: 1246, unit: 'mF', name: 'Millifarad', name_english: 'Millifarad'},
    {value: 1247, unit: 'μF', name: 'Mikrofarad', name_english: 'Microfarad'},
    {value: 1248, unit: 'nF', name: 'Nanofarad', name_english: 'Nanofarad'},
    {value: 1249, unit: 'pF', name: 'Picofarad', name_english: 'Picofarad'},
    {value: 1250, unit: 'F/m', name: 'Farad pro Meter', name_english: 'Farad per meter'},
    {value: 1251, unit: 'μF/m', name: 'Microfarad pro Meter', name_english: 'Microfarad per meter'},
    {value: 1252, unit: 'nF/m', name: 'Nanofarad pro Meter', name_english: 'Nanofarad per meter'},
    {value: 1253, unit: 'pF/m', name: 'Picofarad pro Meter', name_english: 'Picofarad per meter'},
    {value: 1254, unit: 'C·m', name: 'Coulomb mal Meter', name_english: 'Coulomb meter'},
    {value: 1255, unit: 'A/m2', name: 'Ampere pro Quadratmeter', name_english: 'Amperes per square meter'},
    {value: 1256, unit: 'MA/m2', name: 'Megaampere pro Quadratmeter', name_english: 'Megaamperes per square meter'},
    {value: 1257, unit: 'A/cm2', name: 'Ampere pro Quadratzentimeter', name_english: 'Amperes per square centimeter'},
    {value: 1258, unit: 'kA/m2', name: 'Kiloampere pro Quadratmeter', name_english: 'Kiloamperes per square meter'},
    {value: 1259, unit: 'A/m', name: 'Ampere pro Meter', name_english: 'Amperes per meter'},
    {value: 1260, unit: 'kA/m', name: 'Kiloampere pro Meter', name_english: 'Kiloamperes per meter'},
    {value: 1261, unit: 'A/cm', name: 'Ampere pro Zentimeter', name_english: 'Amperes per centimeter'},
    {value: 1262, unit: 'T', name: 'Tesla', name_english: 'Tesla'},
    {value: 1263, unit: 'mT', name: 'Millitesla', name_english: 'Millitesla'},
    {value: 1264, unit: 'μT', name: 'Mikrotesla', name_english: 'Microtesla'},
    {value: 1265, unit: 'nT', name: 'Nanotesla', name_english: 'Nanotesla'},
    {value: 1266, unit: 'Wb', name: 'Weber', name_english: 'Weber'},
    {value: 1267, unit: 'mWb', name: 'Milliweber', name_english: 'Milliweber'},
    {value: 1268, unit: 'Wb/m', name: 'Weber pro Meter', name_english: 'Webers per meter'},
    {value: 1269, unit: 'kWb/m', name: 'Kiloweber pro Meter', name_english: 'Kilowebers per meter'},
    {value: 1270, unit: 'H', name: 'Henry', name_english: 'Henry'},
    {value: 1271, unit: 'mH', name: 'Millihenry', name_english: 'Millihenry'},
    {value: 1272, unit: 'μH', name: 'Mikrohenry', name_english: 'Microhenry'},
    {value: 1273, unit: 'nH', name: 'Nanohenry', name_english: 'Nanohenry'},
    {value: 1274, unit: 'pH', name: 'Picohenry', name_english: 'Picohenry'},
    {value: 1275, unit: 'H/m', name: 'Henry pro Meter', name_english: 'Henries per meter'},
    {value: 1276, unit: 'μH/m', name: 'Mikrohenry pro Meter', name_english: 'Microhenries per meter'},
    {value: 1277, unit: 'nH/m', name: 'Nanohenry pro Meter', name_english: 'Nanohenries per meter'},
    {value: 1278, unit: 'A·m2', name: 'Ampere mal Quadratmeter', name_english: 'Ampere square meters'},
    {
        value: 1279,
        unit: 'N·m2/A',
        name: 'Newton mal Quadratmeter pro Ampere',
        name_english: 'Newton meter squared per ampere'
    },
    {value: 1280, unit: 'Wb·m', name: 'Weber mal Meter', name_english: 'Weber meter'},
    {value: 1281, unit: 'Ω', name: 'Ohm1', name_english: 'Ohm'},
    {value: 1282, unit: 'GΩ', name: 'GigaOhm1', name_english: 'Gigaohm'},
    {value: 1283, unit: 'MΩ', name: 'MegaOhm1', name_english: 'Megaohm'},
    {value: 1284, unit: 'kΩ', name: 'KiloOhm1', name_english: 'Kiloohm'},
    {value: 1285, unit: 'mΩ', name: 'MilliOhm1', name_english: 'Milliohm'},
    {value: 1286, unit: 'μΩ', name: 'MikroOhm1', name_english: 'Microohm'},
    {value: 1287, unit: 'S', name: 'Siemens', name_english: 'Siemens'},
    {value: 1288, unit: 'kS', name: 'Kilosiemens', name_english: 'Kilosiemens'},
    {value: 1289, unit: 'mS', name: 'Millisiemens', name_english: 'Millisiemens'},
    {value: 1290, unit: 'μS', name: 'Mikrosiemens', name_english: 'Microsiemens'},
    {value: 1291, unit: 'Ω·m', name: 'Ohm mal Meter1', name_english: 'Ohms times meters'},
    {value: 1292, unit: 'GΩ·m', name: 'GigaOhm mal Meter1', name_english: 'Gigaohms times meters'},
    {value: 1293, unit: 'MΩ·m', name: 'MegaOhm mal Meter1', name_english: 'Megaohms times meters1'},
    {value: 1294, unit: 'kΩ·m', name: 'KiloOhm mal Meter1', name_english: 'Kiloohms times meters1'},
    {value: 1295, unit: 'Ω·cm', name: 'Ohm mal Zentimeter1', name_english: 'Ohms times centimeters1'},
    {value: 1296, unit: 'mΩ·m', name: 'MilliOhm mal Meter1', name_english: 'Milliohms times meters1'},
    {value: 1297, unit: 'μΩ·m', name: 'MikroOhm mal Meter1', name_english: 'Microohms times meters1'},
    {value: 1298, unit: 'nΩ·m', name: 'NanoOhm mal Meter1', name_english: 'Nanoohms times meters1'},
    {value: 1299, unit: 'S/m', name: 'Siemens pro Meter', name_english: 'Siemens per meter'},
    {value: 1300, unit: 'MS/m', name: 'Megasiemens pro Meter', name_english: 'Megasiemens per meter'},
    {value: 1301, unit: 'kS/m', name: 'Kilosiemens pro Meter', name_english: 'Kilosiemens per meter'},
    {value: 1302, unit: 'mS/cm', name: 'Millisiemens pro Zentimeter', name_english: 'Millisiemens per centimeter'},
    {value: 1303, unit: 'μS/mm', name: 'Mikrosiemens pro Millimeter', name_english: 'Microsiemens per millimeter'},
    {value: 1304, unit: '1/H', name: 'Pro Henry', name_english: 'Per henry'},
    {value: 1305, unit: 'sr', name: 'Steradiant', name_english: 'Steradian'},
    {value: 1306, unit: 'W/sr', name: 'Watt pro Steradiant', name_english: 'Watts per steradian'},
    {
        value: 1307,
        unit: 'W/(sr·m2)',
        name: 'Watt pro (Steradiant mal Quadratmeter)',
        name_english: 'Watts per (steradian square meter)'
    },
    {value: 1308, unit: 'W/(m2)', name: 'Watt pro Quadratmeter', name_english: 'Watts per square meter'},
    {value: 1309, unit: 'lm', name: 'Lumen', name_english: 'Lumen'},
    {value: 1310, unit: 'lm·s', name: 'Lumensekunde', name_english: 'Lumen second'},
    {value: 1311, unit: 'lm·h', name: 'Lumenstunde', name_english: 'Lumen hour'},
    {value: 1312, unit: 'lm/m2', name: 'Lumen pro Quadratmeter', name_english: 'Lumens per square meter'},
    {value: 1313, unit: 'lm/W', name: 'Lumen pro Watt', name_english: 'Lumens per watt'},
    {value: 1314, unit: 'lx', name: 'Lux', name_english: 'Lux'},
    {value: 1315, unit: 'lx·s', name: 'Luxsekunde', name_english: 'Lux second'},
    {value: 1316, unit: 'cd', name: 'Candela', name_english: 'Candela'},
    {value: 1317, unit: 'cd/m2', name: 'Candela pro Quadratmeter', name_english: 'Candela per square meter'},
    {value: 1318, unit: 'g/s', name: 'Gramm pro Sekunde', name_english: 'Grams per second'},
    {value: 1319, unit: 'g/min', name: 'Gramm pro Minute', name_english: 'Grams per minute'},
    {value: 1320, unit: 'g/h', name: 'Gramm pro Stunde', name_english: 'Grams per hour'},
    {value: 1321, unit: 'g/d', name: 'Gramm pro Tag', name_english: 'Grams per day'},
    {value: 1322, unit: 'kg/s', name: 'Kilogramm pro Sekunde', name_english: 'Kilograms per second'},
    {value: 1323, unit: 'kg/min', name: 'Kilogramm pro Minute', name_english: 'Kilograms per minute'},
    {value: 1324, unit: 'kg/h', name: 'Kilogramm pro Stunde', name_english: 'Kilograms per hour'},
    {value: 1325, unit: 'kg/d', name: 'Kilogramm pro Tag', name_english: 'Kilograms per day'},
    {value: 1326, unit: 't/s', name: 'Metrische Tonne pro Sekunde', name_english: 'Metric tons per second'},
    {value: 1327, unit: 't/min', name: 'Metrische Tonne pro Minute', name_english: 'Metric tons per minute'},
    {value: 1328, unit: 't/h', name: 'Metrische Tonne pro Stunde', name_english: 'Metric tons per hour'},
    {value: 1329, unit: 't/d', name: 'Metrische Tonne pro Tag', name_english: 'Metric tons per day'},
    {value: 1330, unit: 'lb/s', name: 'Pfund pro Sekunde', name_english: 'Pounds per second'},
    {value: 1331, unit: 'lb/min', name: 'Pfund pro Minute', name_english: 'Pounds per minute'},
    {value: 1332, unit: 'lb/h', name: 'Pfund pro Stunde', name_english: 'Pounds per hour'},
    {value: 1333, unit: 'lb/d', name: 'Pfund pro Tag', name_english: 'Pounds per day'},
    {value: 1334, unit: 'STon/s', name: 'US-Tonnen pro Sekunde', name_english: 'US tons per second'},
    {value: 1335, unit: 'STon/min', name: 'US-Tonnen pro Minute', name_english: 'US tons per minute'},
    {value: 1336, unit: 'STon/h', name: 'US-Tonnen pro Stunde', name_english: 'US tons per hour'},
    {value: 1337, unit: 'STon/d', name: 'US-Tonnen pro Tag', name_english: 'US tons per day'},
    {value: 1338, unit: 'LTon/s', name: 'Britische Tonnen pro Sekunde', name_english: 'British tons per second'},
    {value: 1339, unit: 'LTon/min', name: 'Britische Tonnen pro Minute', name_english: 'British tons per minute'},
    {value: 1340, unit: 'LTon/h', name: 'Britische Tonnen pro Stunde', name_english: 'British tons per hour'},
    {value: 1341, unit: 'LTon/d', name: 'Britische Tonnen pro Tag', name_english: 'British tons per day'},
    {value: 1342, unit: '%', name: 'Prozent', name_english: 'Percent'},
    {
        value: 1343,
        unit: '% sol/wt',
        name: 'Prozent Feststoffe pro Gewichtseinheit',
        name_english: 'Percentage solids per weight unit'
    },
    {
        value: 1344,
        unit: '% sol/vol',
        name: 'Prozent Feststoffe pro Volumeneinheit',
        name_english: 'Percentage solids per volume unit'
    },
    {value: 1345, unit: '% stm qual', name: 'Prozent Dampfqualität', name_english: 'Percentage steam quality'},
    {value: 1346, unit: '°Plato', name: 'Grad plato', name_english: 'Degree plato'},
    {value: 1347, unit: 'm3/s', name: 'Kubikmeter pro Sekunde', name_english: 'Cubic meters per second'},
    {value: 1348, unit: 'm3/min', name: 'Kubikmeter pro Minute', name_english: 'Cubic meters per minute'},
    {value: 1349, unit: 'm3/h', name: 'Kubikmeter pro Stunde', name_english: 'Cubic meters per hour'},
    {value: 1350, unit: 'm3/d', name: 'Kubikmeter pro Tag', name_english: 'Cubic meters per day'},
    {value: 1351, unit: 'L/s', name: 'Liter pro Sekunde', name_english: 'Liters per second'},
    {value: 1352, unit: 'L/min', name: 'Liter pro Minute', name_english: 'Liters per minute'},
    {value: 1353, unit: 'L/h', name: 'Liter pro Stunde', name_english: 'Liters per hour'},
    {value: 1354, unit: 'L/d', name: 'Liter pro Tag', name_english: 'Liters per day'},
    {value: 1355, unit: 'ML/d', name: 'Megaliter pro Tag', name_english: 'Megaliters per day'},
    {value: 1356, unit: 'ft3/s', name: 'Kubikfuß pro Sekunde', name_english: 'Cubic feet per second'},
    {value: 1357, unit: 'ft3/m', name: 'Kubikfuß pro Minute', name_english: 'Cubic feet per minute'},
    {value: 1358, unit: 'ft3/h', name: 'Kubikfuß pro Stunde', name_english: 'Cubic feet per hour'},
    {value: 1359, unit: 'ft3/d', name: 'Kubikfuß pro Tag', name_english: 'Cubic feet per day'},
    {
        value: 1360,
        unit: 'ft3/min std',
        name: 'Standard Kubikfuß pro Minute',
        name_english: 'Standard cubic feet per minute'
    },
    {
        value: 1361,
        unit: 'ft3/h std',
        name: 'Standard Kubikfuß pro Stunde',
        name_english: 'Standard cubic feet per hour'
    },
    {value: 1362, unit: 'gal/s', name: 'US-Gallonen pro Sekunde', name_english: 'US gallons per second'},
    {value: 1363, unit: 'gal/min', name: 'US-Gallonen pro Minute', name_english: 'US gallons per minute'},
    {value: 1364, unit: 'gal/h', name: 'US-Gallonen pro Stunde', name_english: 'US gallons per hour'},
    {value: 1365, unit: 'gal/d', name: 'US-Gallonen pro Tag', name_english: 'US gallons per day'},
    {value: 1366, unit: 'Mgal/d', name: 'Mega US-Gallonen pro Tag', name_english: 'Mega US gallons per day'},
    {value: 1367, unit: 'ImpGal/s', name: 'Imperial Gallonen pro Sekunde', name_english: 'Imperial gallons per second'},
    {
        value: 1368,
        unit: 'ImpGal/min',
        name: 'Imperial Gallonen pro Minute',
        name_english: 'Imperial gallons per minute'
    },
    {value: 1369, unit: 'ImpGal/h', name: 'Imperial Gallonen pro Stunde', name_english: 'Imperial gallons per hour'},
    {value: 1370, unit: 'ImpGal/d', name: 'Imperial Gallonen pro Tag', name_english: 'Imperial gallons per day'},
    {value: 1371, unit: 'bbl/s', name: 'Barrel pro Sekunde', name_english: 'Barrels per second'},
    {value: 1372, unit: 'bbl/min', name: 'Barrel pro Minute', name_english: 'Barrels per minute'},
    {value: 1373, unit: 'bbl/h', name: 'Barrel pro Stunde', name_english: 'Barrels per hour'},
    {value: 1374, unit: 'bbl/d', name: 'Barrel pro Tag', name_english: 'Barrels per day'},
    {value: 1375, unit: 'W/m2', name: 'Watt pro Quadratmeter', name_english: 'Watts per square meter'},
    {value: 1376, unit: 'mW/m2', name: 'Milliwatt pro Quadratmeter', name_english: 'Milliwatts per square meter'},
    {value: 1377, unit: 'μW/m2', name: 'Mikrowatt pro Quadratmeter', name_english: 'Microwatts per square meter'},
    {value: 1378, unit: 'pW/m2', name: 'Picowatt pro Quadratmeter', name_english: 'Picowatts per square meter'},
    {
        value: 1379,
        unit: 'Pa·s/m3',
        name: 'Pascalsekunde pro Kubikmeter',
        name_english: 'Pascal seconds per cubic meter'
    },
    {value: 1380, unit: 'N·s/m', name: 'Newtonsekunde pro Meter', name_english: 'Newton seconds per meter'},
    {value: 1381, unit: 'Pa·s/m', name: 'Pascalsekunde pro Meter', name_english: 'Pascal seconds per meter'},
    {value: 1382, unit: 'B', name: 'Bel', name_english: 'Bel'},
    {value: 1383, unit: 'dB', name: 'Dezibel', name_english: 'Decibel'},
    {value: 1384, unit: 'mol', name: 'Mol', name_english: 'Mol'},
    {value: 1385, unit: 'kmol', name: 'Kilomol', name_english: 'Kilomole'},
    {value: 1386, unit: 'mmol', name: 'Millimol', name_english: 'Millimole'},
    {value: 1387, unit: 'μmol', name: 'Mikromol', name_english: 'Micromole'},
    {value: 1388, unit: 'kg/mol', name: 'Kilogramm pro Mol', name_english: 'Kilograms per mole'},
    {value: 1389, unit: 'g/mol', name: 'Gramm pro Mol', name_english: 'Grams per mole'},
    {value: 1390, unit: 'm3/mol', name: 'Kubikmeter pro Mol', name_english: 'Cubic meters per mole'},
    {value: 1391, unit: 'dm3/mol', name: 'Kubikdezimeter pro Mol', name_english: 'Cubic decimeters per mole'},
    {value: 1392, unit: 'cm3/mol', name: 'Kubikzentimeter pro Mol', name_english: 'Cubic centimeters per mole'},
    {value: 1393, unit: 'L/mol', name: 'Liter pro Mol', name_english: 'Liters per mole'},
    {value: 1394, unit: 'J/mol', name: 'Joule pro Mol', name_english: 'Joules per mole'},
    {value: 1395, unit: 'kJ/mol', name: 'Kilojoule pro Mol', name_english: 'Kilojoules per mole'},
    {value: 1396, unit: 'J/(mol·K)', name: 'Joule pro (Mol mal Kelvin)', name_english: 'Joules per mole kelvin'},
    {value: 1397, unit: 'mol/m3', name: 'Mol pro Kubikmeter', name_english: 'Moles per cubic meter'},
    {value: 1398, unit: 'mol/dm3', name: 'Mol pro Kubikdezimeter', name_english: 'Moles per cubic decimeter'},
    {value: 1399, unit: 'mol/L', name: 'Mol pro Liter', name_english: 'Moles per liter'},
    {value: 1400, unit: 'mol/kg', name: 'Mol pro Kilogramm', name_english: 'Moles per kilogram'},
    {value: 1401, unit: 'mmol/kg', name: 'Millimol pro Kilogramm', name_english: 'Millimoles per kilogram'},
    {value: 1402, unit: 'Bq', name: 'Becquerel', name_english: 'Becquerel'},
    {value: 1403, unit: 'MBq', name: 'Megabecquerel', name_english: 'Megabecquerel'},
    {value: 1404, unit: 'kBq', name: 'Kilobecquerel', name_english: 'Kilobecquerel'},
    {value: 1405, unit: 'Bq/kg', name: 'Becquerel pro Kilogramm', name_english: 'Becquerels per kilogram'},
    {value: 1406, unit: 'kBq/kg', name: 'Kilobecquerel pro Kilogramm', name_english: 'Kilobecquerels per kilogram'},
    {value: 1407, unit: 'MBq/kg', name: 'Megabecquerel pro Kilogramm', name_english: 'Megabecquerels per kilogram'},
    {value: 1408, unit: 'Gy', name: 'Grau', name_english: 'Gray'},
    {value: 1409, unit: 'mGy', name: 'Milligray', name_english: 'Milligray'},
    {value: 1410, unit: 'rd', name: 'Rad', name_english: 'Rad'},
    {value: 1411, unit: 'Sv', name: 'Sievert', name_english: 'Sievert'},
    {value: 1412, unit: 'mSv', name: 'Millisievert', name_english: 'Millisievert'},
    {value: 1413, unit: 'rem', name: 'Rem', name_english: 'Rem'},
    {value: 1414, unit: 'C/kg', name: 'Coulomb pro Kilogramm', name_english: 'Coulombs per kilogram'},
    {value: 1415, unit: 'mC/kg', name: 'Millicoulomb pro Kilogramm', name_english: 'Millicoulombs per kilogram'},
    {value: 1416, unit: 'R', name: 'Röntgen', name_english: 'Röntgen'},
    {value: 1417, unit: '1/Jm3', name: 'Magnetische Energiedichte', name_english: 'Density of magnetic energy'},
    {value: 1418, unit: 'e/Vm3', name: '-', name_english: '-'},
    {value: 1419, unit: 'm3/C', name: 'Kubikmeter pro Coulomb', name_english: 'Cubic meters per coulomb'},
    {value: 1420, unit: 'V/K', name: 'Volt pro Kelvin', name_english: 'Volts per kelvin'},
    {value: 1421, unit: 'mV/K', name: 'Millivolt pro Kelvin', name_english: 'Millivolts per kelvin'},
    {value: 1422, unit: 'pH', name: 'pH-Wert', name_english: 'pH value'},
    {value: 1423, unit: 'ppm', name: 'Teile pro Million', name_english: 'Parts per million'},
    {value: 1424, unit: 'ppb', name: 'Teile pro Milliarde', name_english: 'Parts per billion'},
    {value: 1425, unit: 'ppth', name: 'Teile pro Billion', name_english: 'Parts per trillion'},
    {value: 1426, unit: '°Brix', name: 'Grad Brix', name_english: 'Degrees Brix'},
    {value: 1427, unit: '°Ball', name: 'Grad Balling', name_english: 'Degrees Balling'},
    {value: 1428, unit: 'proof/vol', name: 'Proof per volume', name_english: 'Proof per volume'},
    {value: 1429, unit: 'proof/mass', name: 'Proof per mass', name_english: 'Proof per mass'},
    {value: 1430, unit: 'lb/ImpGal', name: 'Pfund pro Imperial Gallone', name_english: 'Pounds per Imperial gallon'},
    {value: 1431, unit: 'kcalth/s', name: 'Kilokalorie pro Sekunde1', name_english: 'Kilocalories per second1'},
    {value: 1432, unit: 'kcalth/min', name: 'Kilokalorie pro Minute1', name_english: 'Kilocalories per minute1'},
    {value: 1433, unit: 'kcalth/h', name: 'Kilokalorie pro Stunde1', name_english: 'Kilocalories per hour1'},
    {value: 1434, unit: 'kcalth/d', name: 'Kilokalorie pro Tag1', name_english: 'Kilocalories per day1'},
    {value: 1435, unit: 'Mcalth/s', name: 'Megakalorie pro Sekunde1', name_english: 'Megacalories per second1'},
    {value: 1436, unit: 'Mcalth/min', name: 'Megakalorie pro Minute1', name_english: 'Megacalories per minute1'},
    {value: 1437, unit: 'Mcalth/d', name: 'Megakalorie pro Tag1', name_english: 'Megacalories per day1'},
    {value: 1438, unit: 'kJ/s', name: 'Kilojoule pro Sekunde', name_english: 'Kilojoules per second'},
    {value: 1439, unit: 'kJ/min', name: 'Kilojoule pro Minute', name_english: 'Kilojoules per minute'},
    {value: 1440, unit: 'kJ/h', name: 'Kilojoule pro Stunde', name_english: 'Kilojoule per hour'},
    {value: 1441, unit: 'kJ/d', name: 'Kilojoule pro Tag', name_english: 'Kilojoules per day'},
    {value: 1442, unit: 'MJ/s', name: 'Megajoule pro Sekunde', name_english: 'Megajoules per second'},
    {value: 1443, unit: 'MJ/min', name: 'Megajoule pro Minute', name_english: 'Megajoules per minute'},
    {value: 1444, unit: 'MJ/d', name: 'Megajoule pro Tag', name_english: 'Megajoules per day'},
    {
        value: 1445,
        unit: 'Btuth/s',
        name: 'Britische thermische Einheit pro Sekunde1',
        name_english: 'British thermal units per second1'
    },
    {
        value: 1446,
        unit: 'Btuth/min',
        name: 'Britische thermische Einheit pro Minute1',
        name_english: 'British thermal units per minute1'
    },
    {
        value: 1447,
        unit: 'Btuth/d',
        name: 'Britische thermische Einheit pro Tag1',
        name_english: 'British thermal units per day1'
    },
    {value: 1448, unit: 'μgal/s', name: 'Mikro US-Gallone pro Sekunde', name_english: 'Micro US gallons per second'},
    {value: 1449, unit: 'mgal/s', name: 'Milli US-Gallone pro Sekunde', name_english: 'Milli US gallons per second'},
    {value: 1450, unit: 'kgal/s', name: 'Kilo US-Gallone pro Sekunde', name_english: 'Kilo US gallons per second'},
    {value: 1451, unit: 'Mgal/s', name: 'Mega US-Gallone pro Sekunde', name_english: 'Mega US gallons per second'},
    {value: 1452, unit: 'μgal/min', name: 'Mikro US-Gallone pro Minute', name_english: 'Micro US gallons per minute'},
    {value: 1453, unit: 'mgal/min', name: 'Milli US-Gallone pro Minute', name_english: 'Milli US gallons per minute'},
    {value: 1454, unit: 'kgal/min', name: 'Kilo US-Gallone pro Minute', name_english: 'Kilo US gallons per minute'},
    {value: 1455, unit: 'Mgal/min', name: 'Mega US-Gallone pro Minute', name_english: 'Mega US gallons per minute'},
    {value: 1456, unit: 'μgal/h', name: 'Mikro US-Gallone pro Stunde', name_english: 'Micro US gallons per hour'},
    {value: 1457, unit: 'mgal/h', name: 'Milli US-Gallone pro Stunde', name_english: 'Milli US gallons per hour'},
    {value: 1458, unit: 'kgal/h', name: 'Kilo US-Gallone pro Stunde', name_english: 'Kilo US gallons per hour'},
    {value: 1459, unit: 'Mgal/h', name: 'Mega US-Gallone pro Stunde', name_english: 'Mega US gallons per hour'},
    {value: 1460, unit: 'μgal/d', name: 'Mikro US-Gallone pro Tag', name_english: 'Micro US gallons per day'},
    {value: 1461, unit: 'mgal/d', name: 'Milli US-Gallone pro Tag', name_english: 'Milli US gallons per day'},
    {value: 1462, unit: 'kgal/d', name: 'Kilo US-Gallone pro Tag', name_english: 'Kilo US gallons per day'},
    {
        value: 1463,
        unit: 'μImpGal/s',
        name: 'Mikro Imperial Gallone pro Sekunde',
        name_english: 'Micro Imperial gallons per second'
    },
    {
        value: 1464,
        unit: 'mImpGal/s',
        name: 'Milli Imperial Gallone pro Sekunde',
        name_english: 'Milli Imperial gallons per second'
    },
    {
        value: 1465,
        unit: 'kImpGal/s',
        name: 'Kilo Imperial Gallone pro Sekunde',
        name_english: 'Kilo Imperial gallons per second'
    },
    {
        value: 1466,
        unit: 'MImpGal/s',
        name: 'Mega Imperial Gallone pro Sekunde',
        name_english: 'Mega Imperial gallons per second'
    },
    {
        value: 1467,
        unit: 'μImpGal/min',
        name: 'Mikro Imperial Gallone pro Minute',
        name_english: 'Micro Imperial gallons per minute'
    },
    {
        value: 1468,
        unit: 'mImpGal/min',
        name: 'Milli Imperial Gallone pro Minute',
        name_english: 'Milli Imperial gallons per minute'
    },
    {
        value: 1469,
        unit: 'kImpGal/min',
        name: 'Kilo Imperial Gallone pro Minute',
        name_english: 'Kilo Imperial gallons per minute'
    },
    {
        value: 1470,
        unit: 'MImpGal/min',
        name: 'Mega Imperial Gallone pro Minute',
        name_english: 'Mega Imperial gallons per minute'
    },
    {
        value: 1471,
        unit: 'μImpGal/h',
        name: 'Mikro Imperial Gallone pro Stunde',
        name_english: 'Micro Imperial gallons per hour'
    },
    {
        value: 1472,
        unit: 'mImpGal/h',
        name: 'Milli Imperial Gallone pro Stunde',
        name_english: 'Milli Imperial gallons per hour'
    },
    {
        value: 1473,
        unit: 'kImpGal/h',
        name: 'Kilo Imperial Gallone pro Stunde',
        name_english: 'Kilo Imperial gallons per hour'
    },
    {
        value: 1474,
        unit: 'MImpGal/h',
        name: 'Mega Imperial Gallone pro Stunde',
        name_english: 'Mega Imperial gallons per hour'
    },
    {
        value: 1475,
        unit: 'μImpgal/d',
        name: 'Mikro Imperial Gallone pro Tag',
        name_english: 'Micro Imperial gallons per day'
    },
    {
        value: 1476,
        unit: 'mImpgal/d',
        name: 'Milli Imperial Gallone pro Tag',
        name_english: 'Milli Imperial gallons per day'
    },
    {
        value: 1477,
        unit: 'kImpgal/d',
        name: 'Kilo Imperial Gallone pro Tag',
        name_english: 'Kilo Imperial gallons per day'
    },
    {
        value: 1478,
        unit: 'MImpgal/d',
        name: 'Mega Imperial Gallone pro Tag',
        name_english: 'Mega Imperial gallons per day'
    },
    {value: 1479, unit: 'μbbl/s', name: 'Mikrobarrel pro Sekunde', name_english: 'Microbarrels per second'},
    {value: 1480, unit: 'mbbl/s', name: 'Millibarrel pro Sekunde', name_english: 'Millibarrels per second'},
    {value: 1481, unit: 'kbbl/s', name: 'Kilobarrel pro Sekunde', name_english: 'Kilobarrels per second'},
    {value: 1482, unit: 'Mbbl/s', name: 'Megabarrel pro Sekunde', name_english: 'Megabarrels per second'},
    {value: 1483, unit: 'μbbl/min', name: 'Mikrobarrel pro Minute', name_english: 'Microbarrels per minute'},
    {value: 1484, unit: 'mbbl/min', name: 'Millibarrel pro Minute', name_english: 'Millibarrels per minute'},
    {value: 1485, unit: 'kbbl/min', name: 'Kilobarrel pro Minute', name_english: 'Kilobarrels per minute'},
    {value: 1486, unit: 'Mbbl/min', name: 'Megabarrel pro Minute', name_english: 'Megabarrels per minute'},
    {value: 1487, unit: 'μbbl/h', name: 'Mikrobarrel pro Stunde', name_english: 'Microbarrels per hour'},
    {value: 1488, unit: 'mbbl/h', name: 'Millibarrel pro Stunde', name_english: 'Millibarrels per hour'},
    {value: 1489, unit: 'kbbl/h', name: 'Kilobarrel pro Stunde', name_english: 'Kilobarrels per hour'},
    {value: 1490, unit: 'Mbbl/h', name: 'Megabarrel pro Stunde', name_english: 'Megabarrels per hour'},
    {value: 1491, unit: 'μbbl/d', name: 'Mikrobarrel pro Tag', name_english: 'Microbarrels per day'},
    {value: 1492, unit: 'mbbl/d', name: 'Millibarrel pro Tag', name_english: 'Millibarrels per day'},
    {value: 1493, unit: 'kbbl/d', name: 'Kilobarrel pro Tag', name_english: 'Kilobarrels per day'},
    {value: 1494, unit: 'Mbbl/d', name: 'Megabarrel pro Tag', name_english: 'Megabarrels per day'},
    {value: 1495, unit: 'μm3/s', name: 'Kubikmikrometer pro Sekunde', name_english: 'Cubic micrometers per second'},
    {value: 1496, unit: 'mm3/s', name: 'Kubikmillimeter pro Sekunde', name_english: 'Cubic millimeters per second'},
    {value: 1497, unit: 'km3/s', name: 'Kubikkilometer pro Sekunde', name_english: 'Cubic kilometers per second'},
    {value: 1498, unit: 'Mm3/s', name: 'Kubikmegameter pro Sekunde', name_english: 'Cubic megameters per second'},
    {value: 1499, unit: 'μm3/min', name: 'Kubikmikrometer pro Minute', name_english: 'Cubic micrometers per minute'},
    {value: 1500, unit: 'mm3/min', name: 'Kubikmillimeter pro Minute', name_english: 'Cubic millimeters per minute'},
    {value: 1501, unit: 'km3/min', name: 'Kubikkilometer pro Minute', name_english: 'Cubic kilometers per minute'},
    {value: 1502, unit: 'mm3/min', name: 'Kubikmegameter pro Minute', name_english: 'Cubic megameters per minute'},
    {value: 1503, unit: 'μm3/h', name: 'Kubikmikrometer pro Stunde', name_english: 'Cubic micrometers per hour'},
    {value: 1504, unit: 'mm3/h', name: 'Kubikmillimeter pro Stunde', name_english: 'Cubic millimeters per hour'},
    {value: 1505, unit: 'km3/h', name: 'Kubikkilometer pro Stunde', name_english: 'Cubic kilometers per hour'},
    {value: 1506, unit: 'Mm3/h', name: 'Kubikmegameter pro Stunde', name_english: 'Cubic megameters per hour'},
    {value: 1507, unit: 'μm3/d', name: 'Kubikmikrometer pro Tag', name_english: 'Cubic micrometers per day'},
    {value: 1508, unit: 'mm3/d', name: 'Kubikmillimeter pro Tag', name_english: 'Cubic millimeters per day'},
    {value: 1509, unit: 'km3/d', name: 'Kubikkilometer pro Tag', name_english: 'Cubic kilometers per day'},
    {value: 1510, unit: 'Mm3/d', name: 'Kubikmegameter pro Tag', name_english: 'Cubic megameters per day'},
    {value: 1511, unit: 'cm3/s', name: 'Kubikzentimeter pro Sekunde', name_english: 'Cubic centimeters per second'},
    {value: 1512, unit: 'cm3/min', name: 'Kubikzentimeter pro Minute', name_english: 'Cubic centimeters per minute'},
    {value: 1513, unit: 'cm3/h', name: 'Kubikzentimeter pro Stunde', name_english: 'Cubic centimeters per hour'},
    {value: 1514, unit: 'cm3/d', name: 'Kubikzentimeter pro Tag', name_english: 'Cubic centimeters per day'},
    {value: 1515, unit: 'kcalth/kg', name: 'Kilokalorie pro Kilogramm1', name_english: 'Kilocalories per kilogram1'},
    {
        value: 1516,
        unit: 'Btuth/lb',
        name: 'Britische thermische Einheit pro Pfund1',
        name_english: 'British thermal units per pound1'
    },
    {value: 1517, unit: 'kL', name: 'Kiloliter', name_english: 'Kiloliter'},
    {value: 1518, unit: 'kL/min', name: 'Kiloliter pro Minute', name_english: 'Kiloliters per minute'},
    {value: 1519, unit: 'kL/h', name: 'Kiloliter pro Stunde', name_english: 'Kiloliters per hour'},
    {value: 1520, unit: 'kL/d', name: 'Kiloliter pro Tag', name_english: 'Kiloliters per day'},
    {value: 1551, unit: 'S/cm', name: 'Siemens pro Zentimeter', name_english: 'Siemens per centimeter'},
    {value: 1552, unit: 'μS/cm', name: 'Mikrosiemens pro Zentimeter', name_english: 'Microsiemens per centimeter'},
    {value: 1553, unit: 'mS/m', name: 'Millisiemens pro Meter', name_english: 'Millisiemens per meter'},
    {value: 1554, unit: 'μS/m', name: 'Mikrosiemens pro Meter', name_english: 'Microsiemens per meter'},
    {value: 1555, unit: 'MΩ · cm', name: 'Megaohm Zentimeter1', name_english: 'Megaohm centimeter1'},
    {value: 1556, unit: 'kΩ · cm', name: 'Kiloohm Zentimeter1', name_english: 'Kiloohm centimeter1'},
    {value: 1557, unit: 'Gew%', name: 'Gewichtprozent', name_english: 'Weight percent'},
    {value: 1558, unit: 'mg/L', name: 'Milligramm pro Liter', name_english: 'Milligram per liter'},
    {value: 1559, unit: 'μg/L', name: 'Mikrogramm pro Liter', name_english: 'Microgram per liter'},
    {value: 1560, unit: '%Sat', name: '-', name_english: 'percent_saturation'},
    {value: 1561, unit: 'vpm', name: '-', name_english: 'volume_parts_per_million'},
    {value: 1562, unit: '%vol', name: 'Volumenprozent', name_english: 'Volume percent'},
    {value: 1563, unit: 'ml/min', name: 'Milliliter pro Minute', name_english: 'Milliliters per minute'},
    {
        value: 1564,
        unit: 'mg/dm3',
        name: 'Milligramm pro Kubikzentimeter',
        name_english: 'Milligrams per cubic centimeter'
    },
    {value: 1565, unit: 'mg/L', name: 'Milligramm pro Liter', name_english: 'Milligram per liter'},
    {value: 1566, unit: 'mg/m3', name: 'Milligramm pro Kubikmeter', name_english: 'Milligrams per cubic meter'},
    {value: 1567, unit: 'ct', name: 'Karat (Juwelen) = 200.0·10-6 kg', name_english: 'Carat (jewels) = 200.0·10-6 kg'},
    {
        value: 1568,
        unit: 'lb (tr)',
        name: 'Pfund (troy or apothecary) = 0.3732417216 kg',
        name_english: 'Pound (troy or apothecary) = 0.3732417216 kg'
    },
    {
        value: 1569,
        unit: 'oz (tr)',
        name: 'Unze (troy or apothecary) = 1/12 lb (tr)',
        name_english: 'Ounce (troy or apothecary) = 1/12 lb (tr)'
    },
    {
        value: 1570,
        unit: 'fl oz (U.S.)',
        name: 'Unze (U.S. fluid) = (1/128) gal',
        name_english: 'Ounce (U.S. fluid) = (1/128) gal'
    },
    {value: 1571, unit: 'cm3', name: 'Kubikzentimeter = 10-6 m3', name_english: 'Cubic centimeter = 10-6 m3'},
    {value: 1572, unit: 'af', name: 'acre foot = 43560 ft3', name_english: 'acre foot = 43560 ft3'},
    {value: 1573, unit: 'm3 normal', name: 'Kubikmeter', name_english: 'Cubic meter'},
    {value: 1574, unit: 'L normal', name: 'Liter', name_english: 'Liter'},
    {value: 1575, unit: 'm3 std.', name: 'Standard Kubikmeter', name_english: 'Standard cubic meter'},
    {value: 1576, unit: 'L std.', name: 'Standard Liter', name_english: 'Standard liter'},
    {value: 1577, unit: 'ml/s', name: 'Milliliter pro Sekunde', name_english: 'Milliliters per second'},
    {value: 1578, unit: 'ml/h', name: 'Milliliter pro Stunde', name_english: 'Milliliters per hour'},
    {value: 1579, unit: 'ml/d', name: 'Milliliter pro Tag', name_english: 'Milliliters per day'},
    {value: 1580, unit: 'af/s', name: 'acre foot pro Sekunde', name_english: 'Acre foot per second'},
    {value: 1581, unit: 'af/min', name: 'acre foot pro Minute', name_english: 'Acre foot per minute'},
    {value: 1582, unit: 'af/h', name: 'acre foot pro Stunde', name_english: 'Acre foot per hour'},
    {value: 1583, unit: 'af/d', name: 'acre foot pro tag', name_english: 'Acre foot per day'},
    {value: 1584, unit: 'fl oz (U.S.)/s', name: 'Unze pro Sekunde', name_english: 'fluid_Ounces per second'},
    {value: 1585, unit: 'fl oz (U.S.) /min', name: 'Unze pro Minute', name_english: 'fluid_Ounces per minute'},
    {value: 1586, unit: 'fl oz (U.S.)/h', name: 'Unze pro Stunde', name_english: 'fluid_Ounces per hour'},
    {value: 1587, unit: 'fl oz (U.S.)/d', name: 'Unze pro Tag', name_english: 'fluid_Ounces per day'},
    {
        value: 1588,
        unit: 'm3/s normal',
        name: 'Normalkubikmeter pro Sekunde',
        name_english: 'Normal cubic meters per second'
    },
    {
        value: 1589,
        unit: 'm3/min normal',
        name: 'Normalkubikmeter pro Minute',
        name_english: 'Normal cubic meters per minute'
    },
    {
        value: 1590,
        unit: 'm3/h normal',
        name: 'Normalkubikmeter pro Stunde',
        name_english: 'Normal cubic meters per hour'
    },
    {value: 1591, unit: 'm3/d normal', name: 'Normalkubikmeter pro Tag', name_english: 'Normal cubic meters per day'},
    {value: 1592, unit: 'L/s normal', name: 'Normalliter pro Sekunde', name_english: 'Normal liters per second'},
    {value: 1593, unit: 'L/min normal', name: 'Normalliter pro Minute', name_english: 'Normal liters per minute'},
    {value: 1594, unit: 'L/h normal', name: 'Normalliter pro Stunde', name_english: 'Normal liters per hour'},
    {value: 1595, unit: 'L/d normal', name: 'Normalliter pro Tag', name_english: 'Normal liters per day'},
    {
        value: 1596,
        unit: 'm3/s std.',
        name: 'Standardkubikmeter pro Sekunde',
        name_english: 'Standard cubic meters per second'
    },
    {
        value: 1597,
        unit: 'm3/min std.',
        name: 'Standardkubikmeter pro Minute',
        name_english: 'Standard cubic meters per minute'
    },
    {
        value: 1598,
        unit: 'm3/h std.',
        name: 'Standardkubikmeter pro Stunde',
        name_english: 'Standard cubic meters per hour'
    },
    {value: 1599, unit: 'm3/d std.', name: 'Standardkubikmeter pro Tag', name_english: 'Standard cubic meters per day'},
    {value: 1600, unit: 'L/s std.', name: 'Standardliter pro Sekunde', name_english: 'Standard liters per second'},
    {value: 1601, unit: 'L/min std.', name: 'Standardliter pro Minute', name_english: 'Standard liters per minute'},
    {value: 1602, unit: 'L/h std.', name: 'Standardliter pro Stunde', name_english: 'Standard liters per hour'},
    {value: 1603, unit: 'L/d std.', name: 'Standardliter pro Tag', name_english: 'Standard liters per day'},
    {
        value: 1604,
        unit: 'ft3/s std.',
        name: 'Standardkubikfuß pro Sekunde',
        name_english: 'Standard cubic feet per second'
    },
    {value: 1605, unit: 'ft3/d std.', name: 'Standardkubikfuß pro Tag', name_english: 'Standard cubic feet per day'},
    {value: 1606, unit: 'oz/s', name: 'Unze pro Sekunde', name_english: 'Ounces per second'},
    {value: 1607, unit: 'oz/min', name: 'Unze pro Minute', name_english: 'Ounces per minute'},
    {value: 1608, unit: 'oz/h', name: 'Unze pro Stunde', name_english: 'Ounces per hour'},
    {value: 1609, unit: 'oz/d', name: 'Unze pro Tag', name_english: 'Ounces per day'},
    {value: 1610, unit: 'Paa', name: 'Pascal (absolut)', name_english: 'Pascal (absolute)'},
    {value: 1611, unit: 'Pag', name: 'Pascal (Gauge)', name_english: 'Pascal (gauge)'},
    {value: 1612, unit: 'GPaa', name: 'Gigapasacal (absolut)', name_english: 'Gigapasacal (absolute)'},
    {value: 1613, unit: 'GPag', name: 'Gigapascal (Gauge)', name_english: 'Gigapascal (gauge)'},
    {value: 1614, unit: 'MPaa', name: 'Megapascal (absolut)', name_english: 'Megapascal (absolute)'},
    {value: 1615, unit: 'MPag', name: 'Mgeapascal (Gauge)', name_english: 'Megapascal (gauge)'},
    {value: 1616, unit: 'kPaa', name: 'Kilopascal (absolut)', name_english: 'Kilopascal (absolute)'},
    {value: 1617, unit: 'kPag', name: 'Kilopascal (Gauge)', name_english: 'Kilopascal (gauge)'},
    {value: 1618, unit: 'mPaa', name: 'Millipascal (absolut)', name_english: 'Millipascal (absolute)'},
    {value: 1619, unit: 'mPag', name: 'Millipascal (Gauge)', name_english: 'Millipascal (gauge)'},
    {value: 1620, unit: 'μPaa', name: 'Micropascal (absolut)', name_english: 'Micropascal (absolute)'},
    {value: 1621, unit: 'μPag', name: 'Micorpascal (Gauge)', name_english: 'Micropascal (gauge)'},
    {value: 1622, unit: 'hPaa', name: 'Hektopascal (absolut)', name_english: 'Hectopascal (absolute)'},
    {value: 1623, unit: 'hPag', name: 'Hektopascal (Gauge)', name_english: 'Hectopascal (gauge)'},
    {value: 1624, unit: 'gf/cm2a', name: '-', name_english: 'gram_force_per_square_centimeter_absolut'},
    {value: 1625, unit: 'gf/cm2g', name: '-', name_english: 'gram_force_per_square_centimeter_gauge'},
    {value: 1626, unit: 'kgf/cm2a', name: '-', name_english: 'kilogram_force_per_square_centimeter_absolut'},
    {value: 1627, unit: 'kgf/cm2g', name: '-', name_english: 'kilogram_force_per_square_centimeter_gauge'},
    {value: 1628, unit: 'SD4°C', name: 'Standarddichte bei 4°C', name_english: 'Standard density at 4°C'},
    {value: 1629, unit: 'SD15°C', name: 'Standarddichte bei 15°C', name_english: 'Standard density at 15°C'},
    {value: 1630, unit: 'SD20°C', name: 'Standarddichte bei 20°C', name_english: 'Standard density at 20°C'},
    {value: 1631, unit: 'PS', name: 'Metrische Pferdestärken', name_english: 'Metric horsepower'},
    {value: 1632, unit: 'ppt', name: 'Teile pro Billion = 1012', name_english: 'Parts per trillion = 1012'},
    {value: 1633, unit: 'hl/s', name: 'Hektoliter pro Sekunde', name_english: 'Hectoliters per second'},
    {value: 1634, unit: 'hl/min', name: 'Hektoliter pro Minute', name_english: 'Hectoliters per minute'},
    {value: 1635, unit: 'hl/h', name: 'Hektoliter pro Stunde', name_english: 'Hectoliters per hour'},
    {value: 1636, unit: 'hl/d', name: 'Hektoliter pro Tag', name_english: 'Hectoliters per day'},
    {
        value: 1637,
        unit: 'bbl (liq)/s',
        name: 'Barrel (US flüssig) pro Sekunde',
        name_english: 'Barrels (US liquid) per second'
    },
    {
        value: 1638,
        unit: 'bbl (liq)/min',
        name: 'Barrel (US flüssig) pro Minute',
        name_english: 'Barrels (US liquid) per minute'
    },
    {
        value: 1639,
        unit: 'bbl (liq)/h',
        name: 'Barrel (US flüssig) pro Stunde',
        name_english: 'Barrels (US liquid) per hour'
    },
    {
        value: 1640,
        unit: 'bbl (liq)/d',
        name: 'Barrel (US flüssig) pro Tag',
        name_english: 'Barrels (US liquid) per day'
    },
    {
        value: 1641,
        unit: 'bbl (fed)',
        name: 'Barrel (U.S. federal) = 31 Gallonen',
        name_english: 'Barrel (U.S. federal) = 31 gallons'
    },
    {
        value: 1642,
        unit: 'bbl (fed)/s',
        name: 'Barrel (U.S. federal) pro Sekunde',
        name_english: 'Barrels (US federal) per second'
    },
    {
        value: 1643,
        unit: 'bbl (fed)/min',
        name: 'Barrel (U.S. federal) pro Minute',
        name_english: 'Barrels (US federal) per minute'
    },
    {
        value: 1644,
        unit: 'bbl (fed)/h',
        name: 'Barrel (U.S. federal) pro Stunde',
        name_english: 'Barrels (US federal) per hour'
    },
    {
        value: 1645,
        unit: 'bbl (fed)/d',
        name: 'Barrel (U.S. federal) pro Tag',
        name_english: 'Barrels (US federal) per day'
    },
    {
        value: 1998,
        unit: 'Maßeinheit nicht bekannt',
        name: 'Zu verwenden, wenn bei der Projektierung die Maßeinheit noch nicht bekannt',
        name_english: 'To be used when the unit of measure is not known during configuration'
    },
    {value: 1999, unit: 'spezial', name: 'Spezielle Einheiten', name_english: 'Special units'},

];
