export const Unit = [
    {value: 1000, unit: "K", name: "Kelvin"},
    {value: 1001, unit: "°C", name: "Grad Celsius"},
    {value: 1002, unit: "°F", name: "Grad Fahrenheit"},
    {value: 1005, unit: "°", name: "Grad"},
    {value: 1006, unit: "'", name: "Minute"},
    {value: 1007, unit: "''", name: "Sekunde"},
    {value: 1010, unit: "m", name: "Meter"},
    {value: 1013, unit: "mm", name: "Millimeter"},
    {value: 1018, unit: "ft", name: "Fuß"},
    {value: 1023, unit: "m2", name: "Quadratmeter"},
    {value: 1038, unit: "L", name: "Liter"},
    {value: 1041, unit: "hl", name: "Hektoliter"},
    {value: 1054, unit: "s", name: "Sekunde"},
    {value: 1058, unit: "min", name: "Minute"},
    {value: 1059, unit: "h", name: "Stunde"},
    {value: 1060, unit: "d", name: "Tag"},
    {value: 1061, unit: "m/s", name: "Meter pro Sekunde"},
    {value: 1077, unit: "Hz", name: "Hertz"},
    {value: 1081, unit: "kHz", name: "Kilohertz"},
    {value: 1082, unit: "1/s", name: "Pro Sekunde"},
    {value: 1083, unit: "1/min", name: "Pro Minute"},
    {value: 1088, unit: "kg", name: "Kilogramm"},
    {value: 1092, unit: "t", name: "Metrische Tonne"},
    {value: 1100, unit: "g/cm3", name: "Gramm pro Kubikzentimeter"},
    {value: 1105, unit: "g/L", name: "Gramm pro Liter"},
    {value: 1120, unit: "N", name: "Newton"},
    {value: 1123, unit: "mN", name: "Millinewton"},
    {value: 1130, unit: "Pa", name: "Pascal"},
    {value: 1133, unit: "kPa", name: "Kilopascal"},
    {value: 1137, unit: "bar", name: "Bar"},
    {value: 1138, unit: "mbar", name: "Millibar"},
    {value: 1149, unit: "mmH2O", name: "Millimeter Wassersäule"},
    {value: 1175, unit: "W·h", name: "Wattstunde"},
    {value: 1179, unit: "kW·h", name: "Kilowattstunde"},
    {value: 1181, unit: "kcalth", name: "Kilokalorien"},
    {value: 1190, unit: "kW", name: "Kilowatt"},
    {value: 1209, unit: "A", name: "Ampere"},
    {value: 1211, unit: "mA", name: "Milliampere"},
    {value: 1221, unit: "A·h", name: "Amperestunde"},
    {value: 1240, unit: "V", name: "Volt"},
    {value: 1342, unit: "%", name: "Prozent"},
    {value: 1349, unit: "m3/h", name: "Kubikmeter pro Stunde"},
    {value: 1353, unit: "L/h", name: "Liter pro Stunde"},
    {value: 1384, unit: "mol", name: "Mol"},
    {value: 1422, unit: "pH", name: "pH-Wert"}
];
