@startuml
'https://plantuml.com/class-diagram

class PIDCtrl{
    + readonly communication!: PIDCtrlRuntime
    + sourceMode: SourceModeController
    + opMode: OpModeController
}

PIDCtrl *- PIDCtrlSpec
PIDCtrlSpec ..> PIDCtrlMockup : <<use>>
PIDCtrl *- PIDCtrlMockup
PIDCtrl *- PIDCtrlRuntime
PIDCtrl *- SourceModeController
PIDCtrl *- OpModeController




@enduml
