@startuml
'https://plantuml.com/class-diagram

!include ../../_extensions/osLevelDA/OSLevel.puml

class BinMon{
	+ readonly communication!: BinMonRuntime;
	+ readonly osLevel: OSLevel;
}


BinMon *- BinMonSpec
BinMonSpec ..> BinMonMockup : <<use>>
BinMon *- BinMonMockup
BinMon *- "1" BinMonRuntime
BinMon *- "1" OSLevel



@enduml
