@startuml
'https://plantuml.com/class-diagram
!include monAnaDrv/MonAnaDrv.puml

class AnaDrv{
    + readonly communication!: AnaDrvRuntime
    + readonly sourceMode: SourceModeController
}

AnaDrv *- AnaDrvSpec
AnaDrvSpec ..> AnaDrvMockup : <<use>>
AnaDrv *- AnaDrvMockup

AnaDrv *- "1" AnaDrvRuntime
AnaDrv *- "1" SourceModeController


AnaDrv <|-- MonAnaDrv

@enduml
