@startuml
'https://plantuml.com/class-diagram

class MonAnaDrv{
    + readonly communication!: MonAnaDrvRuntime
    + readonly feedbackMonitoring: FeedbackMonitoring
}

MonAnaDrv *- MonAnaDrvSpec
MonAnaDrvSpec ..> MonAnaDrvMockup : <<use>>
MonAnaDrv *- MonAnaDrvMockup
MonAnaDrv *- "1" MonAnaDrvRuntime
MonAnaDrv *- "1" FeedbackMonitoring
@enduml
