@startuml
'https://plantuml.com/class-diagram
!include DIntMon/DIntMon.puml
class DIntView{
    - readonly scaleSettings: ScaleSettings
    - readonly unitSettings: UnitSettings
}
DIntView *- DIntViewSpec
DIntViewSpec ..> DIntViewMockup : <<use>>
DIntView *- DIntViewMockup


DIntView <|-- DIntMon
DIntView *-- "1" ScaleSettings
DIntView *-- "1" AnaViewRuntime
DIntView *-- "1" UnitSettings

@enduml
