@startuml
skinparam monochrome true
hide empty methods
hide empty fields

class Manager
class Module {
    id
    endpoint
    client: OPCUAClient
}

class Service {
    name: string
    parameters: ServiceParameter[]
}
class ProcessValue
class Strategy

package recipe {
    class Operation
    class Parameter
    class Player
    class Recipe {
        name
        initial_step: Step
    }
    class RecipeRun
    class Condition{
        {static} create()
        {abstract} listen()
        {abstract} clear()
        json()
    }
    'class NotCondition
    'class AndCondition
    'class OrCondition
    'class StateCondition
    'class VariableCondition
    'class TimeCondition {
    '    duration
    '}
    class Step
    class Transition
}

'NotCondition --|> Condition
'AndCondition --|> Condition
'OrCondition --|> Condition
'TimeCondition --|> Condition
'VariableCondition --|> Condition
'StateCondition --|> Condition

RecipeRun --> Recipe
Player o-- Recipe : playlist

Manager "1" o-- "*" Module
Manager "1" o-- "*" Recipe
Manager "1" o-- "*" RecipeRun
Manager "1" o-- "1" Player

Module "1" o-- "*" Service
Module "1" o-- "*" ProcessValue

Service "1" o-- "*" Strategy

Recipe "1" o-- "*" Step
Step "1" o-- "*" Operation
Step "1" o-- "*" Transition

Transition --> Step : nextStep
Transition --> Condition

Operation --> Service
Operation --> Parameter
Operation --> VirtualService

class VirtualService {
}

@enduml