@startuml
skinparam monochrome true

package "Module (PEA)" as PEA {
    [Services] - [OPC UA Server]
}

node "Process Orchestation Layer (POL)" {
    package "polaris-backend" as backend {
        [NodeJs]
    }

    package "polaris-frontend" as frontend {
        [Angular] <-> [NodeJs] : HTTP, Websocket
    }

    package "polaris-interface" {
        () interface as if
    }
    
    package "mtp-converter" {
        [NodeJs/Python]
    }
}


if .. [NodeJs] : import
if .. [Angular] : import

[OPC UA Server] <--> [NodeJs] : OPC UA

[Services] .> [NodeJs/Python]: MTP
[NodeJs/Python] .> [NodeJs] : JSON

@enduml
