@startuml
skinparam monochrome true

package "Module (PEA)" {
    [Services] -- [OPC UA Server]
}

node "Process Orchestation Layer (POL)" {
    package "polaris-backend" {
        [Express] - [Manager/Module/Service]
        [Manager/Module/Service] - [OPC UA Client]
    }

    package "polaris-frontend" {
        [Angular] -right- [Express] : HTTP, Websocket
    }

    package "polaris-interface" {
        () interface as if
    }
}

if .. [Express] : import
if .. [Angular] : import

[OPC UA Server] <-left-> [OPC UA Client] : OPC UA

(MTP) <.. [Services]
(MTP) ..> [Manager/Module/Service]

@enduml