@startuml

skinparam monochrome true

title ServiceState <i>STARTING</i>


(*) --> ===t1===
note right
t1
  R1.Fill.state==IDLE
  D1.DoseAmount.state=IDLE
  T1.Temper.state==IDLE
end note


===t1=== --> state1
note right
Operations
  R1.Fill.start()
  D1.DoseAmount.start(100ml)
  T1.Temper.start(30°C)
end note

state1 --> ==t3==

==t2== --> state2
note right
operations
  D1.DoseAmount.reset()
end note

state2 --> ==t3==
note right
t3
  D1.DoseAmount.state==IDLE &&
  T1.Temper.state==EXECUTE
end note

state1 --> ===t2===
note right
t2
  D1.DoseAmount.state==COMPLETED
end note


==t3== --> (*)
@enduml
