@startuml
'https://plantuml.com/class-diagram
!include PIDCtrl/PIDCtrl.puml
!include ./vlv/Vlv.puml
!include ./drv/Drv.puml

abstract class ActiveElement

ActiveElement <|-- PIDCtrl
ActiveElement <|-- Vlv
ActiveElement <|-- Drv

ActiveElement *- ActiveElementSpec
ActiveElementSpec ..> ActiveElementMockup : <<use>>
ActiveElement *- ActiveElementMockup

abstract class Vlv
abstract class Drv

@enduml
