@startuml
'https://plantuml.com/class-diagram
!include ./servParam/ServParam.puml
!include man/anaMan/AnaMan.puml
!include man/binMan/BinMan.puml
!include man/dintMan/DIntMan.puml
!include ../../../recipe/step/operation/Parameter.puml

class OperationElement{

    + readonly communication!: InputElementRuntime
    + parameterRequest: Parameter | undefined
    + requestedValue = ''

}

OperationElement *- OperationElementSpec
OperationElementSpec ..> OperationElementMockup : <<use>>
OperationElement *- OperationElementMockup

OperationElement <|-- ServParam
OperationElement <|-- AnaMan
OperationElement <|-- BinMan
OperationElement <|-- DIntMan

@enduml
