@startuml

[*] --> Internal
[*] --> Manual

Manual : SrcManAct = 1
Manual : SrcIntAct = 0

Internal : SrcManAct = 0
Internal : SrcIntAct = 1

Manual -> Internal : SrcIntAut(if SrcChannel) \n SrcIntAut(if  not SrcChannel)
Internal -> Manual  : SrcManAut(if SrcChannel) \n SrcManOp(if  not SrcChannel)


@enduml
