@startuml
'https://plantuml.com/class-diagram
!include ../../_extensions/limitMonitoringDA/LimitMonitoring.puml
!include ../../_extensions/osLevelDA/OSLevel.puml

class AnaMon{
    + communication!: AnaMonRuntime
    + limitMonitoring: LimitMonitoring
    + osLevel: OSLevel
}
AnaMon *- AnaMonSpec
AnaMonSpec ..> AnaMonMockup : <<use>>
AnaMon *-- "1" AnaMonMockup
AnaMon *-- "1" AnaMonRuntime
AnaMon *-- "1" LimitMonitoring
AnaMon *-- "1" OSLevel



@enduml
