@startuml
'https://plantuml.com/class-diagram
!include monBinVlv/MonBinVlv.puml

class BinVlv{
	+ readonly communication!: BinVlvRuntime;
}

BinVlv *- BinVlvSpec
BinVlvSpec ..> BinVlvMockup : <<use>>
BinVlv *- BinVlvMockup
BinVlv *- BinVlvRuntime

BinVlv <|-- MonBinVlv

@enduml
