@startuml
'https://plantuml.com/class-diagram

!include ../../../_extensions/scaleSettingsDA/ScaleSettings.puml
!include ../../../_extensions/unitDA/UnitSettings.puml
!include ../../../_extensions/valueLimitationDA/ValueLimitation.puml

class AnaServParam{
    + readonly communication!: AnaServParamRuntime
    + readonly scaleSettings: ScaleSettings
    + readonly unitSettings: UnitSettings
    + readonly valueLimitation: ValueLimitation
}
AnaServParam *- AnaServParamSpec
AnaServParamSpec ..> AnaServParamMockup : <<use>>
AnaServParam *- AnaServParamMockup

AnaServParam *- AnaServParamRuntime
AnaServParam *- ScaleSettings
AnaServParam *- UnitSettings
AnaServParam *- ValueLimitation
@enduml
