@startuml
'https://plantuml.com/class-diagram
!include anaServParam/AnaServParam.puml
!include binServParam/BinServParam.puml
!include dIntServParam/DIntServParam.puml
!include stringServParam/StringServParam.puml

!include ../../_extensions/serviceSourceModeDA/ServiceSourceModeController.puml
!include ../../_extensions/opModeDA/opModeController.puml
!include ../../_extensions/wqcDA/WQC.puml

class ServParam{
    + readonly communication!: ServParamRuntime
    + readonly serviceSourceMode: ServiceSourceModeController
    + readonly serviceOpMode: OpModeController
    + readonly wqc: WQC
}

ServParam *- ServParamSpec
ServParamSpec ..> ServParamMockup : <<use>>
ServParam *- ServParamMockup

ServParam *- ServParamRuntime
ServParam *- ServiceSourceModeController
ServParam *- OpModeController
ServParam *- WQC


ServParam <|-- AnaServParam
ServParam <|-- BinServParam
ServParam <|-- DIntServParam
ServParam <|-- StringServParam

@enduml
