@startuml
'https://plantuml.com/class-diagram
!include ../../../_extensions/scaleSettingsDA/ScaleSettings.puml
!include ../../../_extensions/unitDA/UnitSettings.puml

class AnaProcessValueIn{
    + readonly communication!: AnaProcessValueInRuntime
    - readonly scaleSettings: ScaleSettings
    - readonly unitSettings: UnitSettings
}

AnaProcessValueIn *- AnaProcessValueInSpec
AnaProcessValueInSpec ..> AnaProcessValueInMockup : <<use>>
AnaProcessValueIn *- AnaProcessValueInMockup

AnaProcessValueIn *- AnaProcessValueInRuntime
AnaProcessValueIn *- ScaleSettings
AnaProcessValueIn *- UnitSettings


@enduml
