@startuml
'https://plantuml.com/class-diagram

!include ../../../_extensions/sourceModeDA/SourceModeController.puml
!include ../../../_extensions/wqcDA/WQC.puml
class DIntManInt{
    + readonly communication!: DIntManIntRuntime
    + readonly sourceMode: SourceModeController
    + readonly wqc: WQC
}

DIntManInt *- DIntManIntSpec
DIntManIntSpec ..> DIntManIntMockup : <<use>>
DIntManInt *- DIntManIntMockup

DIntManInt *- DIntManIntRuntime
DIntManInt *- WQC
DIntManInt *- SourceModeController

@enduml
