@startuml
'https://plantuml.com/class-diagram
!include ../../../_extensions/scaleSettingsDA/ScaleSettings.puml
!include ../../../_extensions/unitDA/UnitSettings.puml
!include ../../../_extensions/valueLimitationDA/ValueLimitation.puml

class DIntServParam{
    + readonly communication!: DIntServParamRuntime
    + readonly scaleSettings: ScaleSettings
    + readonly unitSettings: UnitSettings
    + readonly valueLimitation: ValueLimitation
}
DIntServParam *- DIntServParamSpec
DIntServParamSpec ..> DIntServParamMockup : <<use>>
DIntServParam *- DIntServParamMockup

DIntServParam *- DIntServParamRuntime
DIntServParam *- ScaleSettings
DIntServParam *- UnitSettings
DIntServParam *- ValueLimitation
@enduml
