@startuml
'https://plantuml.com/class-diagram
class StringServParam{
  + readonly communication!: BinServParamRuntime

}
StringServParam *- StringServParamSpec
StringServParamSpec ..> StringServParamMockup : <<use>>
StringServParam *- StringServParamMockup

StringServParam *- StringServParamRuntime

@enduml
