@startuml
'https://plantuml.com/class-diagram

class ScaleSettings{
    - dAController: any
    - initialize(): void
    + scaleSettingsToJson(): ParameterInterface
}

ScaleSettings *- ScaleSettingDASpec
ScaleSettingDASpec ..> ScaleSettingDAMockup : <<use>>
ScaleSettings *- ScaleSettingDAMockup

@enduml
