@startuml
'https://plantuml.com/class-diagram

class PEA{
    id
    endpoint
    client: OPCUAClient
}

PEA *-- "0..*" DataAssembly
PEA *-- "0..*" ServiceSet
PEA *-- "0..*" TextSet
PEA *-- "0..*" HMISet

@enduml
