@startuml
'https://plantuml.com/class-diagram
!include ./dataAssembly/DataAssemblyController.puml
!include ./serviceSet/service/service.puml
!include ./connection/OpcUaConnection.puml



class PEAController{
    + //readonly// options: PEAOptions
    + //readonly// id: string
    + //readonly// pimadIdentifier: string
    + //readonly// name: string;

    +  services: Service[]
    + variables: DataAssemblyController[]
    + protected: boolean
    + connection: OpcUaConnection

    - //readonly// description: string
    - //readonly// hmiUrl: string
    - //readonly// logger: Category

    + updateConnection(options: ServerSettingsOptions): void
    + getService(serviceName: string): Service
    + getServiceStates(): ServiceInterface[]
    + //async// connectAndSubscribe(): Promise<void>
    + //async// disconnectAndSubscribe(): Promise<void>
    + json(): PEAInterface
    + isConnected(): boolean
    + listenToDataAssembly(dataAssemblyName: string, variableName: string): DataItemEmitter
    + abort(): Promise<void[]>
    + pause(): Promise<void[]>
    + resume(): Promise<void[]>
    + stop(): Promise<void[]>
    + reset(): Promise<void[]>

    - subscribeToAllVariables(): Promise<DataAssemblyController[]>
    - unsubscribeFromAllVariables(): void
    - subscribeToAllServices(): Promise<StrictEventEmitter<EventEmitter, ServiceEvents, ServiceEvents, "addEventListener" | "removeEventListener", "on" | "addListener" | "removeListener" | "once" | "emit">[]>
    - unsubscribeFromAllServices(): void


}

PEAController *-- "0..*" DataAssemblyController
PEAController *-- "0..*" Service
PEAController *-- "1" OpcUaConnection

PEAEmitter <|-- PEAController


@enduml
