@startuml
'https://plantuml.com/class-diagram


class LimitMonitoring{
    - dAController: any
    - initialize(): void
}

LimitMonitoring *- LimitMonitoringDASpec
LimitMonitoringDASpec ..> LimitMonitoringDAMockup : <<use>>
LimitMonitoring *- LimitMonitoringDAMockup
@enduml
