@startuml
'https://plantuml.com/class-diagram

class MonBinDrv{
   + readonly communication!: MonBinDrvRuntime
   + readonly feedbackMonitoring: FeedbackMonitoring
}
MonBinDrv *- MonBinDrvSpec
MonBinDrvSpec ..> MonBinDrvMockup : <<use>>
MonBinDrv *- MonBinDrvMockup
MonBinDrv *- "1" MonBinDrvRuntime
MonBinDrv *- "1" FeedbackMonitoring


@enduml
