@startuml
'https://plantuml.com/class-diagram

class MonAnaVlv{
   + readonly communication!: MonAnaVlvRuntime
   + readonly feedbackMonitoring: FeedbackMonitoring
 }
MonAnaVlv *- MonAnaVlvSpec
MonAnaVlvSpec ..> MonAnaVlvMockup : <<use>>
MonAnaVlv *- MonAnaVlvMockup
MonAnaVlv *- FeedbackMonitoring


@enduml
