@startuml
'https://plantuml.com/class-diagram

class OpModeController{
    - dAController: any
    - initialize(): void
}

OpModeController *- OpModeDASpec
OpModeDASpec ..> OpModeDAMockup : <<use>>
OpModeController *- OpModeDAMockup

@enduml
