@startuml
'https://plantuml.com/class-diagram

class Reset{
    - dAController: any
    - initialize(): void
}

Reset *- ResetDASpec
ResetDASpec ..> ResetDAMockup : <<use>>
Reset *- ResetDAMockup
@enduml
