@startuml
'https://plantuml.com/class-diagram


class Interlock{
    - dAController: any
    - initialize(): void
}

Interlock *- InterlockDASpec
InterlockDASpec ..> InterlockDAMockup : <<use>>
Interlock *- InterlockDAMockup

@enduml
