@startuml
'https://plantuml.com/class-diagram
!include feedbackMonitoringDA/FeedbackMonitoring.puml
!include interlockDA/Interlock.puml
!include limitMonitoringDA/LimitMonitoring.puml
!include opModeDA/OpModeController.puml
!include osLevelDA/OSLevel.puml
!include resetDA/Reset.puml
!include scaleSettingsDA/ScaleSettings.puml
!include serviceSourceModeDA/ServiceSourceModeController.puml
!include sourceModeDA/SourceModeController.puml
!include unitDA/UnitSettings.puml
!include valueLimitationDA/ValueLimitation.puml
!include wqcDA/WQC.puml

abstract class DataAssemblyController

DataAssemblyController "0..1" o-- FeedbackMonitoringDA
DataAssemblyController "0..1" o-- InterlockDA
DataAssemblyController "0..1" o-- LimitMonitoringDA
DataAssemblyController "0..1" o-- OpModeDA
DataAssemblyController "0..1" o-- OSLevelDA
DataAssemblyController "0..1" o-- ResetDA
DataAssemblyController "0..1" o-- ScaleSettingDA
DataAssemblyController "0..1" o-- ServiceSourceModeDA
DataAssemblyController "0..1" o-- SourceModeDA
DataAssemblyController "0..1" o-- UnitDA
DataAssemblyController "0..1" o-- ValueLimitationDA
DataAssemblyController "0..1" o-- WQCDA

@enduml
