@startuml
title Start Service
participant Operator
participant POL
participant Service

Operator->POL: Start (sendCommand('start'))

POL->Service: if(!StateChannel) StateOpOp 0->1
Service->POL: acknowledge 1->0

POL->Service: Start

@enduml
